/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.clean_energy_tools.openadr_3_types_swagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Body of POST request to /auth/token. Note snake case per https://www.rfc-editor.org/rfc/rfc6749 
 */
@Schema(description = "Body of POST request to /auth/token. Note snake case per https://www.rfc-editor.org/rfc/rfc6749 ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-09-25T13:48:17.242221925+03:00[Europe/Bucharest]")

public class ClientCredentialRequest {
  /**
   * OAuth2 grant type, must be &#x27;client_credentials&#x27;
   */
  @JsonAdapter(GrantTypeEnum.Adapter.class)
  public enum GrantTypeEnum {
    @SerializedName("client_credentials")
    CLIENT_CREDENTIALS("client_credentials");

    private String value;

    GrantTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static GrantTypeEnum fromValue(String input) {
      for (GrantTypeEnum b : GrantTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<GrantTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final GrantTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public GrantTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return GrantTypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("grant_type")
  private GrantTypeEnum grantType = null;

  @SerializedName("client_id")
  private String clientId = null;

  @SerializedName("client_secret")
  private String clientSecret = null;

  @SerializedName("scope")
  private String scope = null;

  public ClientCredentialRequest grantType(GrantTypeEnum grantType) {
    this.grantType = grantType;
    return this;
  }

   /**
   * OAuth2 grant type, must be &#x27;client_credentials&#x27;
   * @return grantType
  **/
  @Schema(example = "client_credentials", required = true, description = "OAuth2 grant type, must be 'client_credentials'")
  public GrantTypeEnum getGrantType() {
    return grantType;
  }

  public void setGrantType(GrantTypeEnum grantType) {
    this.grantType = grantType;
  }

  public ClientCredentialRequest clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * client ID to exchange for bearer token.
   * @return clientId
  **/
  @Schema(example = "ven_client_99", required = true, description = "client ID to exchange for bearer token.")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public ClientCredentialRequest clientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
    return this;
  }

   /**
   * client secret to exchange for bearer token.
   * @return clientSecret
  **/
  @Schema(example = "ven_secret_99", required = true, description = "client secret to exchange for bearer token.")
  public String getClientSecret() {
    return clientSecret;
  }

  public void setClientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
  }

  public ClientCredentialRequest scope(String scope) {
    this.scope = scope;
    return this;
  }

   /**
   * application defined scope.
   * @return scope
  **/
  @Schema(example = "read_all", description = "application defined scope.")
  public String getScope() {
    return scope;
  }

  public void setScope(String scope) {
    this.scope = scope;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientCredentialRequest clientCredentialRequest = (ClientCredentialRequest) o;
    return Objects.equals(this.grantType, clientCredentialRequest.grantType) &&
        Objects.equals(this.clientId, clientCredentialRequest.clientId) &&
        Objects.equals(this.clientSecret, clientCredentialRequest.clientSecret) &&
        Objects.equals(this.scope, clientCredentialRequest.scope);
  }

  @Override
  public int hashCode() {
    return Objects.hash(grantType, clientId, clientSecret, scope);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientCredentialRequest {\n");
    
    sb.append("    grantType: ").append(toIndentedString(grantType)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
