/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.clean_energy_tools.openadr_3_types_swagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Contextual information used to interpret event valuesMap values. E.g. a PRICE payload simply contains a price value, an associated descriptor provides necessary context such as units and currency. 
 */
@Schema(description = "Contextual information used to interpret event valuesMap values. E.g. a PRICE payload simply contains a price value, an associated descriptor provides necessary context such as units and currency. ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-09-25T13:48:17.242221925+03:00[Europe/Bucharest]")

public class EventPayloadDescriptor implements AnyOfprogramRequestPayloadDescriptorsItems {
  /**
   * Used as discriminator.
   */
  @JsonAdapter(ObjectTypeEnum.Adapter.class)
  public enum ObjectTypeEnum {
    @SerializedName("EVENT_PAYLOAD_DESCRIPTOR")
    EVENT_PAYLOAD_DESCRIPTOR("EVENT_PAYLOAD_DESCRIPTOR");

    private String value;

    ObjectTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static ObjectTypeEnum fromValue(String input) {
      for (ObjectTypeEnum b : ObjectTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<ObjectTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ObjectTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public ObjectTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return ObjectTypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("objectType")
  private ObjectTypeEnum objectType = null;

  @SerializedName("payloadType")
  private String payloadType = null;

  @SerializedName("units")
  private String units = null;

  @SerializedName("currency")
  private String currency = null;

  public EventPayloadDescriptor objectType(ObjectTypeEnum objectType) {
    this.objectType = objectType;
    return this;
  }

   /**
   * Used as discriminator.
   * @return objectType
  **/
  @Schema(required = true, description = "Used as discriminator.")
  public ObjectTypeEnum getObjectType() {
    return objectType;
  }

  public void setObjectType(ObjectTypeEnum objectType) {
    this.objectType = objectType;
  }

  public EventPayloadDescriptor payloadType(String payloadType) {
    this.payloadType = payloadType;
    return this;
  }

   /**
   * Represents the nature of values.  See enumerations in Definitions for defined string values, or use privately defined strings 
   * @return payloadType
  **/
  @Schema(example = "PRICE", required = true, description = "Represents the nature of values.  See enumerations in Definitions for defined string values, or use privately defined strings ")
  public String getPayloadType() {
    return payloadType;
  }

  public void setPayloadType(String payloadType) {
    this.payloadType = payloadType;
  }

  public EventPayloadDescriptor units(String units) {
    this.units = units;
    return this;
  }

   /**
   * Get units
   * @return units
  **/
  @Schema(description = "")
  public String getUnits() {
    return units;
  }

  public void setUnits(String units) {
    this.units = units;
  }

  public EventPayloadDescriptor currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Currency of price payload.
   * @return currency
  **/
  @Schema(example = "USD", description = "Currency of price payload.")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventPayloadDescriptor eventPayloadDescriptor = (EventPayloadDescriptor) o;
    return Objects.equals(this.objectType, eventPayloadDescriptor.objectType) &&
        Objects.equals(this.payloadType, eventPayloadDescriptor.payloadType) &&
        Objects.equals(this.units, eventPayloadDescriptor.units) &&
        Objects.equals(this.currency, eventPayloadDescriptor.currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(objectType, payloadType, units, currency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventPayloadDescriptor {\n");
    
    sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
    sb.append("    payloadType: ").append(toIndentedString(payloadType)).append("\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
