/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.clean_energy_tools.openadr_3_types_swagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * Defines temporal aspects of intervals. A start of \&quot;0001-01-01\&quot; or \&quot;0001-01-01T00:00:00\&quot; may indicate &#x27;now&#x27;. See User Guide. A duration of \&quot;P9999Y\&quot; may indicate infinity. See User Guide. A randomizeStart indicates absolute range of client applied offset to start. See User Guide. 
 */
@Schema(description = "Defines temporal aspects of intervals. A start of \"0001-01-01\" or \"0001-01-01T00:00:00\" may indicate 'now'. See User Guide. A duration of \"P9999Y\" may indicate infinity. See User Guide. A randomizeStart indicates absolute range of client applied offset to start. See User Guide. ")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-09-25T13:48:17.242221925+03:00[Europe/Bucharest]")

public class IntervalPeriod {
  @SerializedName("start")
  private OffsetDateTime start = null;

  @SerializedName("duration")
  private String duration = null;

  @SerializedName("randomizeStart")
  private String randomizeStart = null;

  public IntervalPeriod start(OffsetDateTime start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @Schema(description = "")
  public OffsetDateTime getStart() {
    return start;
  }

  public void setStart(OffsetDateTime start) {
    this.start = start;
  }

  public IntervalPeriod duration(String duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @Schema(description = "")
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public IntervalPeriod randomizeStart(String randomizeStart) {
    this.randomizeStart = randomizeStart;
    return this;
  }

   /**
   * Get randomizeStart
   * @return randomizeStart
  **/
  @Schema(description = "")
  public String getRandomizeStart() {
    return randomizeStart;
  }

  public void setRandomizeStart(String randomizeStart) {
    this.randomizeStart = randomizeStart;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntervalPeriod intervalPeriod = (IntervalPeriod) o;
    return Objects.equals(this.start, intervalPeriod.start) &&
        Objects.equals(this.duration, intervalPeriod.duration) &&
        Objects.equals(this.randomizeStart, intervalPeriod.randomizeStart);
  }

  @Override
  public int hashCode() {
    return Objects.hash(start, duration, randomizeStart);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntervalPeriod {\n");
    
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    randomizeStart: ").append(toIndentedString(randomizeStart)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
