/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.clean_energy_tools.openadr_3_types_swagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MQTT broker OAuth2 Bearer Token authentication details
 */
@Schema(description = "MQTT broker OAuth2 Bearer Token authentication details")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-09-25T13:48:17.242221925+03:00[Europe/Bucharest]")

public class MqttNotifierAuthenticationOauth2BearerToken implements OneOfmqttNotifierBindingObjectAuthentication {
  /**
   * Specifies OAuth2 bearer token authentication
   */
  @JsonAdapter(MethodEnum.Adapter.class)
  public enum MethodEnum {
    @SerializedName("OAUTH2_BEARER_TOKEN")
    OAUTH2_BEARER_TOKEN("OAUTH2_BEARER_TOKEN");

    private String value;

    MethodEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static MethodEnum fromValue(String input) {
      for (MethodEnum b : MethodEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<MethodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final MethodEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public MethodEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return MethodEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("method")
  private MethodEnum method = null;

  @SerializedName("username")
  private String username = null;

  public MqttNotifierAuthenticationOauth2BearerToken method(MethodEnum method) {
    this.method = method;
    return this;
  }

   /**
   * Specifies OAuth2 bearer token authentication
   * @return method
  **/
  @Schema(required = true, description = "Specifies OAuth2 bearer token authentication")
  public MethodEnum getMethod() {
    return method;
  }

  public void setMethod(MethodEnum method) {
    this.method = method;
  }

  public MqttNotifierAuthenticationOauth2BearerToken username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Either the distinguished string \&quot;{clientID}\&quot;, or any other literal string
   * @return username
  **/
  @Schema(required = true, description = "Either the distinguished string \"{clientID}\", or any other literal string")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MqttNotifierAuthenticationOauth2BearerToken mqttNotifierAuthenticationOauth2BearerToken = (MqttNotifierAuthenticationOauth2BearerToken) o;
    return Objects.equals(this.method, mqttNotifierAuthenticationOauth2BearerToken.method) &&
        Objects.equals(this.username, mqttNotifierAuthenticationOauth2BearerToken.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(method, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MqttNotifierAuthenticationOauth2BearerToken {\n");
    
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
