/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.clean_energy_tools.openadr_3_types_swagger.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Types of objects addressable through API.
 */
@JsonAdapter(ObjectTypes.Adapter.class)
public enum ObjectTypes {
  @SerializedName("PROGRAM")
  PROGRAM("PROGRAM"),
  @SerializedName("EVENT")
  EVENT("EVENT"),
  @SerializedName("REPORT")
  REPORT("REPORT"),
  @SerializedName("SUBSCRIPTION")
  SUBSCRIPTION("SUBSCRIPTION"),
  @SerializedName("VEN")
  VEN("VEN"),
  @SerializedName("RESOURCE")
  RESOURCE("RESOURCE");

  private String value;

  ObjectTypes(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ObjectTypes fromValue(String input) {
    for (ObjectTypes b : ObjectTypes.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ObjectTypes> {
    @Override
    public void write(final JsonWriter jsonWriter, final ObjectTypes enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public ObjectTypes read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return ObjectTypes.fromValue((String)(value));
    }
  }
}
