/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.clean_energy_tools.openadr_3_types_swagger.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.clean_energy_tools.openadr_3_types_swagger.model.Interval;
import io.github.clean_energy_tools.openadr_3_types_swagger.model.IntervalPeriod;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Report data associated with a resource.
 */
@Schema(description = "Report data associated with a resource.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-09-25T13:48:17.242221925+03:00[Europe/Bucharest]")

public class ReportRequestResources {
  @SerializedName("resourceName")
  private String resourceName = null;

  @SerializedName("intervalPeriod")
  private IntervalPeriod intervalPeriod = null;

  @SerializedName("intervals")
  private List<Interval> intervals = new ArrayList<Interval>();

  public ReportRequestResources resourceName(String resourceName) {
    this.resourceName = resourceName;
    return this;
  }

   /**
   * Get resourceName
   * @return resourceName
  **/
  @Schema(required = true, description = "")
  public String getResourceName() {
    return resourceName;
  }

  public void setResourceName(String resourceName) {
    this.resourceName = resourceName;
  }

  public ReportRequestResources intervalPeriod(IntervalPeriod intervalPeriod) {
    this.intervalPeriod = intervalPeriod;
    return this;
  }

   /**
   * Get intervalPeriod
   * @return intervalPeriod
  **/
  @Schema(description = "")
  public IntervalPeriod getIntervalPeriod() {
    return intervalPeriod;
  }

  public void setIntervalPeriod(IntervalPeriod intervalPeriod) {
    this.intervalPeriod = intervalPeriod;
  }

  public ReportRequestResources intervals(List<Interval> intervals) {
    this.intervals = intervals;
    return this;
  }

  public ReportRequestResources addIntervalsItem(Interval intervalsItem) {
    this.intervals.add(intervalsItem);
    return this;
  }

   /**
   * A list of interval objects.
   * @return intervals
  **/
  @Schema(required = true, description = "A list of interval objects.")
  public List<Interval> getIntervals() {
    return intervals;
  }

  public void setIntervals(List<Interval> intervals) {
    this.intervals = intervals;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportRequestResources reportRequestResources = (ReportRequestResources) o;
    return Objects.equals(this.resourceName, reportRequestResources.resourceName) &&
        Objects.equals(this.intervalPeriod, reportRequestResources.intervalPeriod) &&
        Objects.equals(this.intervals, reportRequestResources.intervals);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceName, intervalPeriod, intervals);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportRequestResources {\n");
    
    sb.append("    resourceName: ").append(toIndentedString(resourceName)).append("\n");
    sb.append("    intervalPeriod: ").append(toIndentedString(intervalPeriod)).append("\n");
    sb.append("    intervals: ").append(toIndentedString(intervals)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
