/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.clean_energy_tools.openadr_3_types_swagger.api;

import io.github.clean_energy_tools.openadr_3_types_swagger.model.Problem;
import io.github.clean_energy_tools.openadr_3_types_swagger.model.Report;
import io.github.clean_energy_tools.openadr_3_types_swagger.model.ReportRequest;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ReportsApi
 */
@Ignore
public class ReportsApiTest {

    private final ReportsApi api = new ReportsApi();

    /**
     * add a report
     *
     * Create a new report in the server.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createReportTest() throws Exception {
        ReportRequest body = null;
        Report response = api.createReport(body);

        // TODO: test validations
    }
    /**
     * delete a report
     *
     * Delete the report specified by the reportID in path.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteReportTest() throws Exception {
        String reportID = null;
        Report response = api.deleteReport(reportID);

        // TODO: test validations
    }
    /**
     * searches all reports
     *
     * List all reports known to the server. May filter results by programID, eventID,  and clientName as query param. Use skip and pagination query params to limit response size. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void searchAllReportsTest() throws Exception {
        String programID = null;
        String eventID = null;
        String clientName = null;
        Integer skip = null;
        Integer limit = null;
        List<Report> response = api.searchAllReports(programID, eventID, clientName, skip, limit);

        // TODO: test validations
    }
    /**
     * searches reports by reportID
     *
     * Fetch the report specified by the reportID in path. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void searchReportsByReportIDTest() throws Exception {
        String reportID = null;
        Report response = api.searchReportsByReportID(reportID);

        // TODO: test validations
    }
    /**
     * update a report
     *
     * Update the report specified by the reportID in path.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateReportTest() throws Exception {
        String reportID = null;
        ReportRequest body = null;
        Report response = api.updateReport(reportID, body);

        // TODO: test validations
    }
}
