/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.clean_energy_tools.openadr_3_types_swagger.api;

import io.github.clean_energy_tools.openadr_3_types_swagger.model.Problem;
import io.github.clean_energy_tools.openadr_3_types_swagger.model.Ven;
import io.github.clean_energy_tools.openadr_3_types_swagger.model.VenRequest;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for VensApi
 */
@Ignore
public class VensApiTest {

    private final VensApi api = new VensApi();

    /**
     * create ven
     *
     * Create a new ven.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createVenTest() throws Exception {
        VenRequest body = null;
        Ven response = api.createVen(body);

        // TODO: test validations
    }
    /**
     * delete  ven
     *
     * Delete the ven specified by venID specified in path.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteVenTest() throws Exception {
        String venID = null;
        Ven response = api.deleteVen(venID);

        // TODO: test validations
    }
    /**
     * search vens by ID
     *
     * Return the ven specified by venID specified in path.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void searchVenByIDTest() throws Exception {
        String venID = null;
        Ven response = api.searchVenByID(venID);

        // TODO: test validations
    }
    /**
     * search vens
     *
     * List all vens. May filter results by venName as query param. May filter results by targets params. Use skip and pagination query params to limit response size. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void searchVensTest() throws Exception {
        String venName = null;
        List<String> targets = null;
        Integer skip = null;
        Integer limit = null;
        List<Ven> response = api.searchVens(venName, targets, skip, limit);

        // TODO: test validations
    }
    /**
     * update  ven
     *
     * Update the ven specified by venID specified in path.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateVenTest() throws Exception {
        String venID = null;
        VenRequest body = null;
        Ven response = api.updateVen(venID, body);

        // TODO: test validations
    }
}
