/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.clean_energy_tools.openadr_3_types.api;

import io.github.clean_energy_tools.openadr_3_types.client.ApiException;
import io.github.clean_energy_tools.openadr_3_types.model.NotifierTopicsResponse;
import io.github.clean_energy_tools.openadr_3_types.model.Problem;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * API tests for MqttNotifierApi
 */
@Disabled
public class MqttNotifierApiTest {

    private final MqttNotifierApi api = new MqttNotifierApi();

    
    /**
     * List all MQTT binding topic names for operations on all events 
     *
     * List all MQTT binding topic names for operations on all events 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAllMqttNotifierTopicsEventsTest() throws ApiException {
        NotifierTopicsResponse response = 
        api.listAllMqttNotifierTopicsEvents();
        
        // TODO: test validations
    }
    
    /**
     * List all MQTT binding topic names for operations on a program 
     *
     * List all MQTT binding topic names for operations on a program 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAllMqttNotifierTopicsProgramTest() throws ApiException {
        String programID = null;
        NotifierTopicsResponse response = 
        api.listAllMqttNotifierTopicsProgram(programID);
        
        // TODO: test validations
    }
    
    /**
     * List all MQTT binding topic names for operations on events for a program 
     *
     * List all MQTT binding topic names for operations on events for a program 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAllMqttNotifierTopicsProgramEventsTest() throws ApiException {
        String programID = null;
        NotifierTopicsResponse response = 
        api.listAllMqttNotifierTopicsProgramEvents(programID);
        
        // TODO: test validations
    }
    
    /**
     * List all MQTT notifier topic names for operations on programs 
     *
     * List all MQTT notifier topic names for operations on programs 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAllMqttNotifierTopicsProgramsTest() throws ApiException {
        NotifierTopicsResponse response = 
        api.listAllMqttNotifierTopicsPrograms();
        
        // TODO: test validations
    }
    
    /**
     * List all MQTT binding topic names for operations on all reports 
     *
     * List all MQTT binding topic names for operations on all reports 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAllMqttNotifierTopicsReportsTest() throws ApiException {
        NotifierTopicsResponse response = 
        api.listAllMqttNotifierTopicsReports();
        
        // TODO: test validations
    }
    
    /**
     * List all MQTT binding topic names for operations on resources 
     *
     * List all MQTT binding topic names for operations on resources 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAllMqttNotifierTopicsResourcesTest() throws ApiException {
        NotifierTopicsResponse response = 
        api.listAllMqttNotifierTopicsResources();
        
        // TODO: test validations
    }
    
    /**
     * List all MQTT binding topic names for operations on all subscriptions 
     *
     * List all MQTT binding topic names for operations on all subscriptions 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAllMqttNotifierTopicsSubscriptionsTest() throws ApiException {
        NotifierTopicsResponse response = 
        api.listAllMqttNotifierTopicsSubscriptions();
        
        // TODO: test validations
    }
    
    /**
     * List all MQTT binding topic names for operations on a ven 
     *
     * List all MQTT binding topic names for operations on a ven 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAllMqttNotifierTopicsVenTest() throws ApiException {
        String venID = null;
        NotifierTopicsResponse response = 
        api.listAllMqttNotifierTopicsVen(venID);
        
        // TODO: test validations
    }
    
    /**
     * List all MQTT binding topic names for operations on events targeted for a ven 
     *
     * List all MQTT binding topic names for operations on events targated for a ven 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAllMqttNotifierTopicsVenEventsTest() throws ApiException {
        String venID = null;
        NotifierTopicsResponse response = 
        api.listAllMqttNotifierTopicsVenEvents(venID);
        
        // TODO: test validations
    }
    
    /**
     * List all MQTT binding topic names for operations on programs targeted for a ven 
     *
     * List all MQTT binding topic names for operations on programs targeted for a ven 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAllMqttNotifierTopicsVenProgramsTest() throws ApiException {
        String venID = null;
        NotifierTopicsResponse response = 
        api.listAllMqttNotifierTopicsVenPrograms(venID);
        
        // TODO: test validations
    }
    
    /**
     * List all MQTT binding topic names for operations on resources for a ven 
     *
     * List all MQTT binding topic names for operations on resources for a ven 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAllMqttNotifierTopicsVenResourcesTest() throws ApiException {
        String venID = null;
        NotifierTopicsResponse response = 
        api.listAllMqttNotifierTopicsVenResources(venID);
        
        // TODO: test validations
    }
    
    /**
     * List all MQTT binding topic names for operations on vens 
     *
     * List all MQTT binding topic names for operations on vens 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAllMqttNotifierTopicsVensTest() throws ApiException {
        NotifierTopicsResponse response = 
        api.listAllMqttNotifierTopicsVens();
        
        // TODO: test validations
    }
    
}
