/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.clean_energy_tools.openadr_3_types.api;

import io.github.clean_energy_tools.openadr_3_types.client.ApiException;
import io.github.clean_energy_tools.openadr_3_types.model.Problem;
import io.github.clean_energy_tools.openadr_3_types.model.Program;
import io.github.clean_energy_tools.openadr_3_types.model.ProgramRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * API tests for ProgramsApi
 */
@Disabled
public class ProgramsApiTest {

    private final ProgramsApi api = new ProgramsApi();

    
    /**
     * create a program
     *
     * Create a new program in the server.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createProgramTest() throws ApiException {
        ProgramRequest programRequest = null;
        Program response = 
        api.createProgram(programRequest);
        
        // TODO: test validations
    }
    
    /**
     * delete a program
     *
     * Delete an existing program with the programID in path.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteProgramTest() throws ApiException {
        String programID = null;
        Program response = 
        api.deleteProgram(programID);
        
        // TODO: test validations
    }
    
    /**
     * searches all programs
     *
     * List all programs known to the server. May filter results by targets params. Use skip and pagination query params to limit response size. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchAllProgramsTest() throws ApiException {
        List<@Size(min = 1, max = 128)String> targets = null;
        Integer skip = null;
        Integer limit = null;
        List<Program> response = 
        api.searchAllPrograms(targets, skip, limit);
        
        // TODO: test validations
    }
    
    /**
     * searches programs by program ID
     *
     * Fetch the program specified by the programID in path. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchProgramByProgramIdTest() throws ApiException {
        String programID = null;
        Program response = 
        api.searchProgramByProgramId(programID);
        
        // TODO: test validations
    }
    
    /**
     * update a program
     *
     * Update an existing program with the programID in path.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateProgramTest() throws ApiException {
        String programID = null;
        ProgramRequest programRequest = null;
        Program response = 
        api.updateProgram(programID, programRequest);
        
        // TODO: test validations
    }
    
}
