/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.clean_energy_tools.openadr_3_types_swagger.api;

import io.github.clean_energy_tools.openadr_3_types_swagger.client.ApiCallback;
import io.github.clean_energy_tools.openadr_3_types_swagger.client.ApiClient;
import io.github.clean_energy_tools.openadr_3_types_swagger.client.ApiException;
import io.github.clean_energy_tools.openadr_3_types_swagger.client.ApiResponse;
import io.github.clean_energy_tools.openadr_3_types_swagger.client.Configuration;
import io.github.clean_energy_tools.openadr_3_types_swagger.client.Pair;
import io.github.clean_energy_tools.openadr_3_types_swagger.client.ProgressRequestBody;
import io.github.clean_energy_tools.openadr_3_types_swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.github.clean_energy_tools.openadr_3_types_swagger.model.Problem;
import io.github.clean_energy_tools.openadr_3_types_swagger.model.Program;
import io.github.clean_energy_tools.openadr_3_types_swagger.model.ProgramRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ProgramsApi {
    private ApiClient apiClient;

    public ProgramsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ProgramsApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for createProgram
     * @param body program item to add. (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call createProgramCall(ProgramRequest body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = body;
        
        // create path and map variables
        String localVarPath = "/programs";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "bearerAuth", "oAuth2ClientCredentials" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call createProgramValidateBeforeCall(ProgramRequest body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        com.squareup.okhttp.Call call = createProgramCall(body, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * create a program
     * Create a new program in the server.
     * @param body program item to add. (optional)
     * @return Program
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Program createProgram(ProgramRequest body) throws ApiException {
        ApiResponse<Program> resp = createProgramWithHttpInfo(body);
        return resp.getData();
    }

    /**
     * create a program
     * Create a new program in the server.
     * @param body program item to add. (optional)
     * @return ApiResponse&lt;Program&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Program> createProgramWithHttpInfo(ProgramRequest body) throws ApiException {
        com.squareup.okhttp.Call call = createProgramValidateBeforeCall(body, null, null);
        Type localVarReturnType = new TypeToken<Program>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * create a program (asynchronously)
     * Create a new program in the server.
     * @param body program item to add. (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call createProgramAsync(ProgramRequest body, final ApiCallback<Program> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = createProgramValidateBeforeCall(body, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Program>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for deleteProgram
     * @param programID Object ID of the program object. (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call deleteProgramCall(String programID, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/programs/{programID}"
            .replaceAll("\\{" + "programID" + "\\}", apiClient.escapeString(programID.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "bearerAuth", "oAuth2ClientCredentials" };
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call deleteProgramValidateBeforeCall(String programID, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'programID' is set
        if (programID == null) {
            throw new ApiException("Missing the required parameter 'programID' when calling deleteProgram(Async)");
        }
        
        com.squareup.okhttp.Call call = deleteProgramCall(programID, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * delete a program
     * Delete an existing program with the programID in path.
     * @param programID Object ID of the program object. (required)
     * @return Program
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Program deleteProgram(String programID) throws ApiException {
        ApiResponse<Program> resp = deleteProgramWithHttpInfo(programID);
        return resp.getData();
    }

    /**
     * delete a program
     * Delete an existing program with the programID in path.
     * @param programID Object ID of the program object. (required)
     * @return ApiResponse&lt;Program&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Program> deleteProgramWithHttpInfo(String programID) throws ApiException {
        com.squareup.okhttp.Call call = deleteProgramValidateBeforeCall(programID, null, null);
        Type localVarReturnType = new TypeToken<Program>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * delete a program (asynchronously)
     * Delete an existing program with the programID in path.
     * @param programID Object ID of the program object. (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call deleteProgramAsync(String programID, final ApiCallback<Program> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = deleteProgramValidateBeforeCall(programID, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Program>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for searchAllPrograms
     * @param targets Indicates targets (optional)
     * @param skip number of records to skip for pagination. (optional)
     * @param limit maximum number of records to return. (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call searchAllProgramsCall(List<String> targets, Integer skip, Integer limit, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/programs";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (targets != null)
        localVarCollectionQueryParams.addAll(apiClient.parameterToPairs("multi", "targets", targets));
        if (skip != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("skip", skip));
        if (limit != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("limit", limit));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "bearerAuth", "oAuth2ClientCredentials" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call searchAllProgramsValidateBeforeCall(List<String> targets, Integer skip, Integer limit, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        com.squareup.okhttp.Call call = searchAllProgramsCall(targets, skip, limit, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * searches all programs
     * List all programs known to the server. May filter results by targets params. Use skip and pagination query params to limit response size. 
     * @param targets Indicates targets (optional)
     * @param skip number of records to skip for pagination. (optional)
     * @param limit maximum number of records to return. (optional)
     * @return List&lt;Program&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<Program> searchAllPrograms(List<String> targets, Integer skip, Integer limit) throws ApiException {
        ApiResponse<List<Program>> resp = searchAllProgramsWithHttpInfo(targets, skip, limit);
        return resp.getData();
    }

    /**
     * searches all programs
     * List all programs known to the server. May filter results by targets params. Use skip and pagination query params to limit response size. 
     * @param targets Indicates targets (optional)
     * @param skip number of records to skip for pagination. (optional)
     * @param limit maximum number of records to return. (optional)
     * @return ApiResponse&lt;List&lt;Program&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<Program>> searchAllProgramsWithHttpInfo(List<String> targets, Integer skip, Integer limit) throws ApiException {
        com.squareup.okhttp.Call call = searchAllProgramsValidateBeforeCall(targets, skip, limit, null, null);
        Type localVarReturnType = new TypeToken<List<Program>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * searches all programs (asynchronously)
     * List all programs known to the server. May filter results by targets params. Use skip and pagination query params to limit response size. 
     * @param targets Indicates targets (optional)
     * @param skip number of records to skip for pagination. (optional)
     * @param limit maximum number of records to return. (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call searchAllProgramsAsync(List<String> targets, Integer skip, Integer limit, final ApiCallback<List<Program>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = searchAllProgramsValidateBeforeCall(targets, skip, limit, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<Program>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for searchProgramByProgramId
     * @param programID Object ID of the program object. (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call searchProgramByProgramIdCall(String programID, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/programs/{programID}"
            .replaceAll("\\{" + "programID" + "\\}", apiClient.escapeString(programID.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "bearerAuth", "oAuth2ClientCredentials" };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call searchProgramByProgramIdValidateBeforeCall(String programID, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'programID' is set
        if (programID == null) {
            throw new ApiException("Missing the required parameter 'programID' when calling searchProgramByProgramId(Async)");
        }
        
        com.squareup.okhttp.Call call = searchProgramByProgramIdCall(programID, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * searches programs by program ID
     * Fetch the program specified by the programID in path. 
     * @param programID Object ID of the program object. (required)
     * @return Program
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Program searchProgramByProgramId(String programID) throws ApiException {
        ApiResponse<Program> resp = searchProgramByProgramIdWithHttpInfo(programID);
        return resp.getData();
    }

    /**
     * searches programs by program ID
     * Fetch the program specified by the programID in path. 
     * @param programID Object ID of the program object. (required)
     * @return ApiResponse&lt;Program&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Program> searchProgramByProgramIdWithHttpInfo(String programID) throws ApiException {
        com.squareup.okhttp.Call call = searchProgramByProgramIdValidateBeforeCall(programID, null, null);
        Type localVarReturnType = new TypeToken<Program>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * searches programs by program ID (asynchronously)
     * Fetch the program specified by the programID in path. 
     * @param programID Object ID of the program object. (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call searchProgramByProgramIdAsync(String programID, final ApiCallback<Program> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = searchProgramByProgramIdValidateBeforeCall(programID, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Program>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for updateProgram
     * @param programID Object ID of the program object. (required)
     * @param body program item to update. (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call updateProgramCall(String programID, ProgramRequest body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = body;
        
        // create path and map variables
        String localVarPath = "/programs/{programID}"
            .replaceAll("\\{" + "programID" + "\\}", apiClient.escapeString(programID.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "bearerAuth", "oAuth2ClientCredentials" };
        return apiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call updateProgramValidateBeforeCall(String programID, ProgramRequest body, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'programID' is set
        if (programID == null) {
            throw new ApiException("Missing the required parameter 'programID' when calling updateProgram(Async)");
        }
        
        com.squareup.okhttp.Call call = updateProgramCall(programID, body, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * update a program
     * Update an existing program with the programID in path.
     * @param programID Object ID of the program object. (required)
     * @param body program item to update. (optional)
     * @return Program
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Program updateProgram(String programID, ProgramRequest body) throws ApiException {
        ApiResponse<Program> resp = updateProgramWithHttpInfo(programID, body);
        return resp.getData();
    }

    /**
     * update a program
     * Update an existing program with the programID in path.
     * @param programID Object ID of the program object. (required)
     * @param body program item to update. (optional)
     * @return ApiResponse&lt;Program&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Program> updateProgramWithHttpInfo(String programID, ProgramRequest body) throws ApiException {
        com.squareup.okhttp.Call call = updateProgramValidateBeforeCall(programID, body, null, null);
        Type localVarReturnType = new TypeToken<Program>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * update a program (asynchronously)
     * Update an existing program with the programID in path.
     * @param programID Object ID of the program object. (required)
     * @param body program item to update. (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call updateProgramAsync(String programID, ProgramRequest body, final ApiCallback<Program> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = updateProgramValidateBeforeCall(programID, body, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Program>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
