/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.github.clean_energy_tools.openadr_3_types.api;

import io.github.clean_energy_tools.openadr_3_types.client.ApiClient;
import io.github.clean_energy_tools.openadr_3_types.client.ApiException;
import io.github.clean_energy_tools.openadr_3_types.client.ApiResponse;
import io.github.clean_energy_tools.openadr_3_types.client.Configuration;
import io.github.clean_energy_tools.openadr_3_types.client.Pair;

import io.github.clean_energy_tools.openadr_3_types.model.AuthServerInfo;
import io.github.clean_energy_tools.openadr_3_types.model.ClientCredentialResponse;
import io.github.clean_energy_tools.openadr_3_types.model.Problem;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import javax.validation.constraints.*;
import javax.validation.Valid;

import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-23T09:35:23.176897405+03:00[Europe/Bucharest]", comments = "Generator version: 7.14.0")
public class AuthApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public AuthApi() {
    this(Configuration.getDefaultApiClient());
  }

  public AuthApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * fetch a token
   * Return an access token based on clientID and clientSecret.
   * @param grantType OAuth2 grant type, must be &#39;client_credentials&#39; (required)
   * @param clientId client ID to exchange for bearer token. (required)
   * @param clientSecret client secret to exchange for bearer token. (required)
   * @param scope application defined scope. (optional)
   * @return ClientCredentialResponse
   * @throws ApiException if fails to make API call
   */
  public ClientCredentialResponse fetchToken(@javax.annotation.Nonnull String grantType, @javax.annotation.Nonnull String clientId, @javax.annotation.Nonnull String clientSecret, @javax.annotation.Nullable String scope) throws ApiException {
    ApiResponse<ClientCredentialResponse> localVarResponse = fetchTokenWithHttpInfo(grantType, clientId, clientSecret, scope);
    return localVarResponse.getData();
  }

  /**
   * fetch a token
   * Return an access token based on clientID and clientSecret.
   * @param grantType OAuth2 grant type, must be &#39;client_credentials&#39; (required)
   * @param clientId client ID to exchange for bearer token. (required)
   * @param clientSecret client secret to exchange for bearer token. (required)
   * @param scope application defined scope. (optional)
   * @return ApiResponse&lt;ClientCredentialResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ClientCredentialResponse> fetchTokenWithHttpInfo(@javax.annotation.Nonnull String grantType, @javax.annotation.Nonnull String clientId, @javax.annotation.Nonnull String clientSecret, @javax.annotation.Nullable String scope) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = fetchTokenRequestBuilder(grantType, clientId, clientSecret, scope);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("fetchToken", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<ClientCredentialResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<ClientCredentialResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ClientCredentialResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder fetchTokenRequestBuilder(@javax.annotation.Nonnull String grantType, @javax.annotation.Nonnull String clientId, @javax.annotation.Nonnull String clientSecret, @javax.annotation.Nullable String scope) throws ApiException {
    // verify the required parameter 'grantType' is set
    if (grantType == null) {
      throw new ApiException(400, "Missing the required parameter 'grantType' when calling fetchToken");
    }
    // verify the required parameter 'clientId' is set
    if (clientId == null) {
      throw new ApiException(400, "Missing the required parameter 'clientId' when calling fetchToken");
    }
    // verify the required parameter 'clientSecret' is set
    if (clientSecret == null) {
      throw new ApiException(400, "Missing the required parameter 'clientSecret' when calling fetchToken");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/auth/token";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    List<NameValuePair> formValues = new ArrayList<>();
    if (grantType != null) {
        formValues.add(new BasicNameValuePair("grant_type", grantType.toString()));
    }
    if (clientId != null) {
        formValues.add(new BasicNameValuePair("client_id", clientId.toString()));
    }
    if (clientSecret != null) {
        formValues.add(new BasicNameValuePair("client_secret", clientSecret.toString()));
    }
    if (scope != null) {
        formValues.add(new BasicNameValuePair("scope", scope.toString()));
    }
    HttpEntity entity = new UrlEncodedFormEntity(formValues, java.nio.charset.StandardCharsets.UTF_8);
    ByteArrayOutputStream formOutputStream = new ByteArrayOutputStream();
    try {
        entity.writeTo(formOutputStream);
    } catch (IOException e) {
        throw new RuntimeException(e);
    }
    localVarRequestBuilder
        .header("Content-Type", entity.getContentType().getValue())
        .method("POST", HttpRequest.BodyPublishers
            .ofInputStream(() -> new ByteArrayInputStream(formOutputStream.toByteArray())));
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * fetch server info
   * Return the URL of the token endpoint.
   * @return AuthServerInfo
   * @throws ApiException if fails to make API call
   */
  public AuthServerInfo getAuthServerInfo() throws ApiException {
    ApiResponse<AuthServerInfo> localVarResponse = getAuthServerInfoWithHttpInfo();
    return localVarResponse.getData();
  }

  /**
   * fetch server info
   * Return the URL of the token endpoint.
   * @return ApiResponse&lt;AuthServerInfo&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<AuthServerInfo> getAuthServerInfoWithHttpInfo() throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getAuthServerInfoRequestBuilder();
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getAuthServerInfo", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<AuthServerInfo>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<AuthServerInfo>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<AuthServerInfo>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getAuthServerInfoRequestBuilder() throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/auth/server";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
