/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.github.clean_energy_tools.openadr_3_types.api;

import io.github.clean_energy_tools.openadr_3_types.client.ApiClient;
import io.github.clean_energy_tools.openadr_3_types.client.ApiException;
import io.github.clean_energy_tools.openadr_3_types.client.ApiResponse;
import io.github.clean_energy_tools.openadr_3_types.client.Configuration;
import io.github.clean_energy_tools.openadr_3_types.client.Pair;

import io.github.clean_energy_tools.openadr_3_types.model.NotifierTopicsResponse;
import io.github.clean_energy_tools.openadr_3_types.model.Problem;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import javax.validation.constraints.*;
import javax.validation.Valid;

import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-23T09:35:23.176897405+03:00[Europe/Bucharest]", comments = "Generator version: 7.14.0")
public class MqttNotifierApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public MqttNotifierApi() {
    this(Configuration.getDefaultApiClient());
  }

  public MqttNotifierApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * List all MQTT binding topic names for operations on all events 
   * List all MQTT binding topic names for operations on all events 
   * @return NotifierTopicsResponse
   * @throws ApiException if fails to make API call
   */
  public NotifierTopicsResponse listAllMqttNotifierTopicsEvents() throws ApiException {
    ApiResponse<NotifierTopicsResponse> localVarResponse = listAllMqttNotifierTopicsEventsWithHttpInfo();
    return localVarResponse.getData();
  }

  /**
   * List all MQTT binding topic names for operations on all events 
   * List all MQTT binding topic names for operations on all events 
   * @return ApiResponse&lt;NotifierTopicsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<NotifierTopicsResponse> listAllMqttNotifierTopicsEventsWithHttpInfo() throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listAllMqttNotifierTopicsEventsRequestBuilder();
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listAllMqttNotifierTopicsEvents", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<NotifierTopicsResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<NotifierTopicsResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<NotifierTopicsResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listAllMqttNotifierTopicsEventsRequestBuilder() throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/notifiers/mqtt/topics/events";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List all MQTT binding topic names for operations on a program 
   * List all MQTT binding topic names for operations on a program 
   * @param programID objectID of the program object (required)
   * @return NotifierTopicsResponse
   * @throws ApiException if fails to make API call
   */
  public NotifierTopicsResponse listAllMqttNotifierTopicsProgram(@javax.annotation.Nonnull String programID) throws ApiException {
    ApiResponse<NotifierTopicsResponse> localVarResponse = listAllMqttNotifierTopicsProgramWithHttpInfo(programID);
    return localVarResponse.getData();
  }

  /**
   * List all MQTT binding topic names for operations on a program 
   * List all MQTT binding topic names for operations on a program 
   * @param programID objectID of the program object (required)
   * @return ApiResponse&lt;NotifierTopicsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<NotifierTopicsResponse> listAllMqttNotifierTopicsProgramWithHttpInfo(@javax.annotation.Nonnull String programID) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listAllMqttNotifierTopicsProgramRequestBuilder(programID);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listAllMqttNotifierTopicsProgram", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<NotifierTopicsResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<NotifierTopicsResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<NotifierTopicsResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listAllMqttNotifierTopicsProgramRequestBuilder(@javax.annotation.Nonnull String programID) throws ApiException {
    // verify the required parameter 'programID' is set
    if (programID == null) {
      throw new ApiException(400, "Missing the required parameter 'programID' when calling listAllMqttNotifierTopicsProgram");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/notifiers/mqtt/topics/programs/{programID}"
        .replace("{programID}", ApiClient.urlEncode(programID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List all MQTT binding topic names for operations on events for a program 
   * List all MQTT binding topic names for operations on events for a program 
   * @param programID Object ID of the program object (required)
   * @return NotifierTopicsResponse
   * @throws ApiException if fails to make API call
   */
  public NotifierTopicsResponse listAllMqttNotifierTopicsProgramEvents(@javax.annotation.Nonnull String programID) throws ApiException {
    ApiResponse<NotifierTopicsResponse> localVarResponse = listAllMqttNotifierTopicsProgramEventsWithHttpInfo(programID);
    return localVarResponse.getData();
  }

  /**
   * List all MQTT binding topic names for operations on events for a program 
   * List all MQTT binding topic names for operations on events for a program 
   * @param programID Object ID of the program object (required)
   * @return ApiResponse&lt;NotifierTopicsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<NotifierTopicsResponse> listAllMqttNotifierTopicsProgramEventsWithHttpInfo(@javax.annotation.Nonnull String programID) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listAllMqttNotifierTopicsProgramEventsRequestBuilder(programID);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listAllMqttNotifierTopicsProgramEvents", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<NotifierTopicsResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<NotifierTopicsResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<NotifierTopicsResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listAllMqttNotifierTopicsProgramEventsRequestBuilder(@javax.annotation.Nonnull String programID) throws ApiException {
    // verify the required parameter 'programID' is set
    if (programID == null) {
      throw new ApiException(400, "Missing the required parameter 'programID' when calling listAllMqttNotifierTopicsProgramEvents");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/notifiers/mqtt/topics/programs/{programID}/events"
        .replace("{programID}", ApiClient.urlEncode(programID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List all MQTT notifier topic names for operations on programs 
   * List all MQTT notifier topic names for operations on programs 
   * @return NotifierTopicsResponse
   * @throws ApiException if fails to make API call
   */
  public NotifierTopicsResponse listAllMqttNotifierTopicsPrograms() throws ApiException {
    ApiResponse<NotifierTopicsResponse> localVarResponse = listAllMqttNotifierTopicsProgramsWithHttpInfo();
    return localVarResponse.getData();
  }

  /**
   * List all MQTT notifier topic names for operations on programs 
   * List all MQTT notifier topic names for operations on programs 
   * @return ApiResponse&lt;NotifierTopicsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<NotifierTopicsResponse> listAllMqttNotifierTopicsProgramsWithHttpInfo() throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listAllMqttNotifierTopicsProgramsRequestBuilder();
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listAllMqttNotifierTopicsPrograms", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<NotifierTopicsResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<NotifierTopicsResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<NotifierTopicsResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listAllMqttNotifierTopicsProgramsRequestBuilder() throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/notifiers/mqtt/topics/programs";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List all MQTT binding topic names for operations on all reports 
   * List all MQTT binding topic names for operations on all reports 
   * @return NotifierTopicsResponse
   * @throws ApiException if fails to make API call
   */
  public NotifierTopicsResponse listAllMqttNotifierTopicsReports() throws ApiException {
    ApiResponse<NotifierTopicsResponse> localVarResponse = listAllMqttNotifierTopicsReportsWithHttpInfo();
    return localVarResponse.getData();
  }

  /**
   * List all MQTT binding topic names for operations on all reports 
   * List all MQTT binding topic names for operations on all reports 
   * @return ApiResponse&lt;NotifierTopicsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<NotifierTopicsResponse> listAllMqttNotifierTopicsReportsWithHttpInfo() throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listAllMqttNotifierTopicsReportsRequestBuilder();
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listAllMqttNotifierTopicsReports", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<NotifierTopicsResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<NotifierTopicsResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<NotifierTopicsResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listAllMqttNotifierTopicsReportsRequestBuilder() throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/notifiers/mqtt/topics/reports";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List all MQTT binding topic names for operations on resources 
   * List all MQTT binding topic names for operations on resources 
   * @return NotifierTopicsResponse
   * @throws ApiException if fails to make API call
   */
  public NotifierTopicsResponse listAllMqttNotifierTopicsResources() throws ApiException {
    ApiResponse<NotifierTopicsResponse> localVarResponse = listAllMqttNotifierTopicsResourcesWithHttpInfo();
    return localVarResponse.getData();
  }

  /**
   * List all MQTT binding topic names for operations on resources 
   * List all MQTT binding topic names for operations on resources 
   * @return ApiResponse&lt;NotifierTopicsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<NotifierTopicsResponse> listAllMqttNotifierTopicsResourcesWithHttpInfo() throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listAllMqttNotifierTopicsResourcesRequestBuilder();
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listAllMqttNotifierTopicsResources", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<NotifierTopicsResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<NotifierTopicsResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<NotifierTopicsResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listAllMqttNotifierTopicsResourcesRequestBuilder() throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/notifiers/mqtt/topics/resources";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List all MQTT binding topic names for operations on all subscriptions 
   * List all MQTT binding topic names for operations on all subscriptions 
   * @return NotifierTopicsResponse
   * @throws ApiException if fails to make API call
   */
  public NotifierTopicsResponse listAllMqttNotifierTopicsSubscriptions() throws ApiException {
    ApiResponse<NotifierTopicsResponse> localVarResponse = listAllMqttNotifierTopicsSubscriptionsWithHttpInfo();
    return localVarResponse.getData();
  }

  /**
   * List all MQTT binding topic names for operations on all subscriptions 
   * List all MQTT binding topic names for operations on all subscriptions 
   * @return ApiResponse&lt;NotifierTopicsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<NotifierTopicsResponse> listAllMqttNotifierTopicsSubscriptionsWithHttpInfo() throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listAllMqttNotifierTopicsSubscriptionsRequestBuilder();
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listAllMqttNotifierTopicsSubscriptions", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<NotifierTopicsResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<NotifierTopicsResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<NotifierTopicsResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listAllMqttNotifierTopicsSubscriptionsRequestBuilder() throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/notifiers/mqtt/topics/subscriptions";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List all MQTT binding topic names for operations on a ven 
   * List all MQTT binding topic names for operations on a ven 
   * @param venID venID of the vens object (required)
   * @return NotifierTopicsResponse
   * @throws ApiException if fails to make API call
   */
  public NotifierTopicsResponse listAllMqttNotifierTopicsVen(@javax.annotation.Nonnull String venID) throws ApiException {
    ApiResponse<NotifierTopicsResponse> localVarResponse = listAllMqttNotifierTopicsVenWithHttpInfo(venID);
    return localVarResponse.getData();
  }

  /**
   * List all MQTT binding topic names for operations on a ven 
   * List all MQTT binding topic names for operations on a ven 
   * @param venID venID of the vens object (required)
   * @return ApiResponse&lt;NotifierTopicsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<NotifierTopicsResponse> listAllMqttNotifierTopicsVenWithHttpInfo(@javax.annotation.Nonnull String venID) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listAllMqttNotifierTopicsVenRequestBuilder(venID);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listAllMqttNotifierTopicsVen", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<NotifierTopicsResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<NotifierTopicsResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<NotifierTopicsResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listAllMqttNotifierTopicsVenRequestBuilder(@javax.annotation.Nonnull String venID) throws ApiException {
    // verify the required parameter 'venID' is set
    if (venID == null) {
      throw new ApiException(400, "Missing the required parameter 'venID' when calling listAllMqttNotifierTopicsVen");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/notifiers/mqtt/topics/vens/{venID}"
        .replace("{venID}", ApiClient.urlEncode(venID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List all MQTT binding topic names for operations on events targeted for a ven 
   * List all MQTT binding topic names for operations on events targated for a ven 
   * @param venID object ID of the ven object (required)
   * @return NotifierTopicsResponse
   * @throws ApiException if fails to make API call
   */
  public NotifierTopicsResponse listAllMqttNotifierTopicsVenEvents(@javax.annotation.Nonnull String venID) throws ApiException {
    ApiResponse<NotifierTopicsResponse> localVarResponse = listAllMqttNotifierTopicsVenEventsWithHttpInfo(venID);
    return localVarResponse.getData();
  }

  /**
   * List all MQTT binding topic names for operations on events targeted for a ven 
   * List all MQTT binding topic names for operations on events targated for a ven 
   * @param venID object ID of the ven object (required)
   * @return ApiResponse&lt;NotifierTopicsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<NotifierTopicsResponse> listAllMqttNotifierTopicsVenEventsWithHttpInfo(@javax.annotation.Nonnull String venID) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listAllMqttNotifierTopicsVenEventsRequestBuilder(venID);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listAllMqttNotifierTopicsVenEvents", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<NotifierTopicsResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<NotifierTopicsResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<NotifierTopicsResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listAllMqttNotifierTopicsVenEventsRequestBuilder(@javax.annotation.Nonnull String venID) throws ApiException {
    // verify the required parameter 'venID' is set
    if (venID == null) {
      throw new ApiException(400, "Missing the required parameter 'venID' when calling listAllMqttNotifierTopicsVenEvents");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/notifiers/mqtt/topics/vens/{venID}/events"
        .replace("{venID}", ApiClient.urlEncode(venID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List all MQTT binding topic names for operations on programs targeted for a ven 
   * List all MQTT binding topic names for operations on programs targeted for a ven 
   * @param venID object ID of the ven object (required)
   * @return NotifierTopicsResponse
   * @throws ApiException if fails to make API call
   */
  public NotifierTopicsResponse listAllMqttNotifierTopicsVenPrograms(@javax.annotation.Nonnull String venID) throws ApiException {
    ApiResponse<NotifierTopicsResponse> localVarResponse = listAllMqttNotifierTopicsVenProgramsWithHttpInfo(venID);
    return localVarResponse.getData();
  }

  /**
   * List all MQTT binding topic names for operations on programs targeted for a ven 
   * List all MQTT binding topic names for operations on programs targeted for a ven 
   * @param venID object ID of the ven object (required)
   * @return ApiResponse&lt;NotifierTopicsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<NotifierTopicsResponse> listAllMqttNotifierTopicsVenProgramsWithHttpInfo(@javax.annotation.Nonnull String venID) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listAllMqttNotifierTopicsVenProgramsRequestBuilder(venID);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listAllMqttNotifierTopicsVenPrograms", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<NotifierTopicsResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<NotifierTopicsResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<NotifierTopicsResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listAllMqttNotifierTopicsVenProgramsRequestBuilder(@javax.annotation.Nonnull String venID) throws ApiException {
    // verify the required parameter 'venID' is set
    if (venID == null) {
      throw new ApiException(400, "Missing the required parameter 'venID' when calling listAllMqttNotifierTopicsVenPrograms");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/notifiers/mqtt/topics/vens/{venID}/programs"
        .replace("{venID}", ApiClient.urlEncode(venID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List all MQTT binding topic names for operations on resources for a ven 
   * List all MQTT binding topic names for operations on resources for a ven 
   * @param venID object ID of the ven object (required)
   * @return NotifierTopicsResponse
   * @throws ApiException if fails to make API call
   */
  public NotifierTopicsResponse listAllMqttNotifierTopicsVenResources(@javax.annotation.Nonnull String venID) throws ApiException {
    ApiResponse<NotifierTopicsResponse> localVarResponse = listAllMqttNotifierTopicsVenResourcesWithHttpInfo(venID);
    return localVarResponse.getData();
  }

  /**
   * List all MQTT binding topic names for operations on resources for a ven 
   * List all MQTT binding topic names for operations on resources for a ven 
   * @param venID object ID of the ven object (required)
   * @return ApiResponse&lt;NotifierTopicsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<NotifierTopicsResponse> listAllMqttNotifierTopicsVenResourcesWithHttpInfo(@javax.annotation.Nonnull String venID) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listAllMqttNotifierTopicsVenResourcesRequestBuilder(venID);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listAllMqttNotifierTopicsVenResources", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<NotifierTopicsResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<NotifierTopicsResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<NotifierTopicsResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listAllMqttNotifierTopicsVenResourcesRequestBuilder(@javax.annotation.Nonnull String venID) throws ApiException {
    // verify the required parameter 'venID' is set
    if (venID == null) {
      throw new ApiException(400, "Missing the required parameter 'venID' when calling listAllMqttNotifierTopicsVenResources");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/notifiers/mqtt/topics/vens/{venID}/resources"
        .replace("{venID}", ApiClient.urlEncode(venID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List all MQTT binding topic names for operations on vens 
   * List all MQTT binding topic names for operations on vens 
   * @return NotifierTopicsResponse
   * @throws ApiException if fails to make API call
   */
  public NotifierTopicsResponse listAllMqttNotifierTopicsVens() throws ApiException {
    ApiResponse<NotifierTopicsResponse> localVarResponse = listAllMqttNotifierTopicsVensWithHttpInfo();
    return localVarResponse.getData();
  }

  /**
   * List all MQTT binding topic names for operations on vens 
   * List all MQTT binding topic names for operations on vens 
   * @return ApiResponse&lt;NotifierTopicsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<NotifierTopicsResponse> listAllMqttNotifierTopicsVensWithHttpInfo() throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listAllMqttNotifierTopicsVensRequestBuilder();
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listAllMqttNotifierTopicsVens", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<NotifierTopicsResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<NotifierTopicsResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<NotifierTopicsResponse>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listAllMqttNotifierTopicsVensRequestBuilder() throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/notifiers/mqtt/topics/vens";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
