/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.github.clean_energy_tools.openadr_3_types.api;

import io.github.clean_energy_tools.openadr_3_types.client.ApiClient;
import io.github.clean_energy_tools.openadr_3_types.client.ApiException;
import io.github.clean_energy_tools.openadr_3_types.client.ApiResponse;
import io.github.clean_energy_tools.openadr_3_types.client.Configuration;
import io.github.clean_energy_tools.openadr_3_types.client.Pair;

import io.github.clean_energy_tools.openadr_3_types.model.Problem;
import io.github.clean_energy_tools.openadr_3_types.model.Report;
import io.github.clean_energy_tools.openadr_3_types.model.ReportRequest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import javax.validation.constraints.*;
import javax.validation.Valid;

import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-23T09:35:23.176897405+03:00[Europe/Bucharest]", comments = "Generator version: 7.14.0")
public class ReportsApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public ReportsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public ReportsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * add a report
   * Create a new report in the server.
   * @param reportRequest report item to add. (optional)
   * @return Report
   * @throws ApiException if fails to make API call
   */
  public Report createReport(@javax.annotation.Nullable ReportRequest reportRequest) throws ApiException {
    ApiResponse<Report> localVarResponse = createReportWithHttpInfo(reportRequest);
    return localVarResponse.getData();
  }

  /**
   * add a report
   * Create a new report in the server.
   * @param reportRequest report item to add. (optional)
   * @return ApiResponse&lt;Report&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Report> createReportWithHttpInfo(@javax.annotation.Nullable ReportRequest reportRequest) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createReportRequestBuilder(reportRequest);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createReport", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<Report>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<Report>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Report>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createReportRequestBuilder(@javax.annotation.Nullable ReportRequest reportRequest) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/reports";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(reportRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * delete a report
   * Delete the report specified by the reportID in path.
   * @param reportID object ID of a report. (required)
   * @return Report
   * @throws ApiException if fails to make API call
   */
  public Report deleteReport(@javax.annotation.Nonnull String reportID) throws ApiException {
    ApiResponse<Report> localVarResponse = deleteReportWithHttpInfo(reportID);
    return localVarResponse.getData();
  }

  /**
   * delete a report
   * Delete the report specified by the reportID in path.
   * @param reportID object ID of a report. (required)
   * @return ApiResponse&lt;Report&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Report> deleteReportWithHttpInfo(@javax.annotation.Nonnull String reportID) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteReportRequestBuilder(reportID);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteReport", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<Report>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<Report>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Report>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteReportRequestBuilder(@javax.annotation.Nonnull String reportID) throws ApiException {
    // verify the required parameter 'reportID' is set
    if (reportID == null) {
      throw new ApiException(400, "Missing the required parameter 'reportID' when calling deleteReport");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/reports/{reportID}"
        .replace("{reportID}", ApiClient.urlEncode(reportID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * searches all reports
   * List all reports known to the server. May filter results by programID, eventID,  and clientName as query param. Use skip and pagination query params to limit response size. 
   * @param programID filter results to reports with programID. (optional)
   * @param eventID filter results to reports with eventID. (optional)
   * @param clientName filter results to reports with clientName. (optional)
   * @param skip number of records to skip for pagination. (optional)
   * @param limit maximum number of records to return. (optional)
   * @return List&lt;Report&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Report> searchAllReports(@javax.annotation.Nullable String programID, @javax.annotation.Nullable String eventID, @javax.annotation.Nullable String clientName, @javax.annotation.Nullable Integer skip, @javax.annotation.Nullable Integer limit) throws ApiException {
    ApiResponse<List<Report>> localVarResponse = searchAllReportsWithHttpInfo(programID, eventID, clientName, skip, limit);
    return localVarResponse.getData();
  }

  /**
   * searches all reports
   * List all reports known to the server. May filter results by programID, eventID,  and clientName as query param. Use skip and pagination query params to limit response size. 
   * @param programID filter results to reports with programID. (optional)
   * @param eventID filter results to reports with eventID. (optional)
   * @param clientName filter results to reports with clientName. (optional)
   * @param skip number of records to skip for pagination. (optional)
   * @param limit maximum number of records to return. (optional)
   * @return ApiResponse&lt;List&lt;Report&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Report>> searchAllReportsWithHttpInfo(@javax.annotation.Nullable String programID, @javax.annotation.Nullable String eventID, @javax.annotation.Nullable String clientName, @javax.annotation.Nullable Integer skip, @javax.annotation.Nullable Integer limit) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = searchAllReportsRequestBuilder(programID, eventID, clientName, skip, limit);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("searchAllReports", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<List<Report>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<List<Report>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<Report>>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder searchAllReportsRequestBuilder(@javax.annotation.Nullable String programID, @javax.annotation.Nullable String eventID, @javax.annotation.Nullable String clientName, @javax.annotation.Nullable Integer skip, @javax.annotation.Nullable Integer limit) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/reports";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "programID";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("programID", programID));
    localVarQueryParameterBaseName = "eventID";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("eventID", eventID));
    localVarQueryParameterBaseName = "clientName";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("clientName", clientName));
    localVarQueryParameterBaseName = "skip";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("skip", skip));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * searches reports by reportID
   * Fetch the report specified by the reportID in path. 
   * @param reportID object ID of a report. (required)
   * @return Report
   * @throws ApiException if fails to make API call
   */
  public Report searchReportsByReportID(@javax.annotation.Nonnull String reportID) throws ApiException {
    ApiResponse<Report> localVarResponse = searchReportsByReportIDWithHttpInfo(reportID);
    return localVarResponse.getData();
  }

  /**
   * searches reports by reportID
   * Fetch the report specified by the reportID in path. 
   * @param reportID object ID of a report. (required)
   * @return ApiResponse&lt;Report&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Report> searchReportsByReportIDWithHttpInfo(@javax.annotation.Nonnull String reportID) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = searchReportsByReportIDRequestBuilder(reportID);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("searchReportsByReportID", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<Report>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<Report>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Report>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder searchReportsByReportIDRequestBuilder(@javax.annotation.Nonnull String reportID) throws ApiException {
    // verify the required parameter 'reportID' is set
    if (reportID == null) {
      throw new ApiException(400, "Missing the required parameter 'reportID' when calling searchReportsByReportID");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/reports/{reportID}"
        .replace("{reportID}", ApiClient.urlEncode(reportID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * update a report
   * Update the report specified by the reportID in path.
   * @param reportID object ID of a report. (required)
   * @param reportRequest Report item to update. (optional)
   * @return Report
   * @throws ApiException if fails to make API call
   */
  public Report updateReport(@javax.annotation.Nonnull String reportID, @javax.annotation.Nullable ReportRequest reportRequest) throws ApiException {
    ApiResponse<Report> localVarResponse = updateReportWithHttpInfo(reportID, reportRequest);
    return localVarResponse.getData();
  }

  /**
   * update a report
   * Update the report specified by the reportID in path.
   * @param reportID object ID of a report. (required)
   * @param reportRequest Report item to update. (optional)
   * @return ApiResponse&lt;Report&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Report> updateReportWithHttpInfo(@javax.annotation.Nonnull String reportID, @javax.annotation.Nullable ReportRequest reportRequest) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateReportRequestBuilder(reportID, reportRequest);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateReport", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<Report>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        String responseBody = new String(localVarResponse.body().readAllBytes());
        localVarResponse.body().close();

        return new ApiResponse<Report>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<Report>() {})
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateReportRequestBuilder(@javax.annotation.Nonnull String reportID, @javax.annotation.Nullable ReportRequest reportRequest) throws ApiException {
    // verify the required parameter 'reportID' is set
    if (reportID == null) {
      throw new ApiException(400, "Missing the required parameter 'reportID' when calling updateReport");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/reports/{reportID}"
        .replace("{reportID}", ApiClient.urlEncode(reportID.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(reportRequest);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
