package io.github.clean_energy_tools.openadr_3_types.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Demo Program Type enum to demonstrate correct package structure.
 * This would be generated by OpenAPI Generator from the specification.
 */
public enum DemoProgramType {
    DEMAND_RESPONSE("DEMAND_RESPONSE"),
    PRICING("PRICING"),
    EMERGENCY("EMERGENCY");
    
    private final String value;
    
    DemoProgramType(String value) {
        this.value = value;
    }
    
    @JsonValue
    public String getValue() {
        return value;
    }
    
    @JsonCreator
    public static DemoProgramType fromValue(String value) {
        for (DemoProgramType type : DemoProgramType.values()) {
            if (type.value.equals(value)) {
                return type;
            }
        }
        throw new IllegalArgumentException("Unexpected value: " + value);
    }
    
    @Override
    public String toString() {
        return value;
    }
}