/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.clean_energy_tools.openadr_3_types.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.clean_energy_tools.openadr_3_types.model.Event;
import io.github.clean_energy_tools.openadr_3_types.model.EventPayloadDescriptor;
import io.github.clean_energy_tools.openadr_3_types.model.Interval;
import io.github.clean_energy_tools.openadr_3_types.model.IntervalPeriod;
import io.github.clean_energy_tools.openadr_3_types.model.Program;
import io.github.clean_energy_tools.openadr_3_types.model.ProgramRequestProgramDescriptionsInner;
import io.github.clean_energy_tools.openadr_3_types.model.Report;
import io.github.clean_energy_tools.openadr_3_types.model.ReportDescriptor;
import io.github.clean_energy_tools.openadr_3_types.model.ReportRequestResourcesInner;
import io.github.clean_energy_tools.openadr_3_types.model.Resource;
import io.github.clean_energy_tools.openadr_3_types.model.Subscription;
import io.github.clean_energy_tools.openadr_3_types.model.SubscriptionRequestObjectOperationsInner;
import io.github.clean_energy_tools.openadr_3_types.model.ValuesMap;
import io.github.clean_energy_tools.openadr_3_types.model.Ven;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import io.github.clean_energy_tools.openadr_3_types.client.ApiClient;
import io.github.clean_energy_tools.openadr_3_types.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-23T09:35:23.176897405+03:00[Europe/Bucharest]", comments = "Generator version: 7.14.0")
@JsonDeserialize(using = NotificationObject.NotificationObjectDeserializer.class)
@JsonSerialize(using = NotificationObject.NotificationObjectSerializer.class)
public class NotificationObject extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(NotificationObject.class.getName());

    public static class NotificationObjectSerializer extends StdSerializer<NotificationObject> {
        public NotificationObjectSerializer(Class<NotificationObject> t) {
            super(t);
        }

        public NotificationObjectSerializer() {
            this(null);
        }

        @Override
        public void serialize(NotificationObject value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class NotificationObjectDeserializer extends StdDeserializer<NotificationObject> {
        public NotificationObjectDeserializer() {
            this(NotificationObject.class);
        }

        public NotificationObjectDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public NotificationObject deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize Event
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (Event.class.equals(Integer.class) || Event.class.equals(Long.class) || Event.class.equals(Float.class) || Event.class.equals(Double.class) || Event.class.equals(Boolean.class) || Event.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((Event.class.equals(Integer.class) || Event.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((Event.class.equals(Float.class) || Event.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (Event.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (Event.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(Event.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'Event'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'Event'", e);
            }

            // deserialize Program
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (Program.class.equals(Integer.class) || Program.class.equals(Long.class) || Program.class.equals(Float.class) || Program.class.equals(Double.class) || Program.class.equals(Boolean.class) || Program.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((Program.class.equals(Integer.class) || Program.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((Program.class.equals(Float.class) || Program.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (Program.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (Program.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(Program.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'Program'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'Program'", e);
            }

            // deserialize Report
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (Report.class.equals(Integer.class) || Report.class.equals(Long.class) || Report.class.equals(Float.class) || Report.class.equals(Double.class) || Report.class.equals(Boolean.class) || Report.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((Report.class.equals(Integer.class) || Report.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((Report.class.equals(Float.class) || Report.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (Report.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (Report.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(Report.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'Report'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'Report'", e);
            }

            // deserialize Resource
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (Resource.class.equals(Integer.class) || Resource.class.equals(Long.class) || Resource.class.equals(Float.class) || Resource.class.equals(Double.class) || Resource.class.equals(Boolean.class) || Resource.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((Resource.class.equals(Integer.class) || Resource.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((Resource.class.equals(Float.class) || Resource.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (Resource.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (Resource.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(Resource.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'Resource'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'Resource'", e);
            }

            // deserialize Subscription
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (Subscription.class.equals(Integer.class) || Subscription.class.equals(Long.class) || Subscription.class.equals(Float.class) || Subscription.class.equals(Double.class) || Subscription.class.equals(Boolean.class) || Subscription.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((Subscription.class.equals(Integer.class) || Subscription.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((Subscription.class.equals(Float.class) || Subscription.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (Subscription.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (Subscription.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(Subscription.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'Subscription'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'Subscription'", e);
            }

            // deserialize Ven
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (Ven.class.equals(Integer.class) || Ven.class.equals(Long.class) || Ven.class.equals(Float.class) || Ven.class.equals(Double.class) || Ven.class.equals(Boolean.class) || Ven.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((Ven.class.equals(Integer.class) || Ven.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((Ven.class.equals(Float.class) || Ven.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (Ven.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (Ven.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(Ven.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'Ven'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'Ven'", e);
            }

            if (match == 1) {
                NotificationObject ret = new NotificationObject();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for NotificationObject: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public NotificationObject getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "NotificationObject cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public NotificationObject() {
        super("oneOf", Boolean.FALSE);
    }

    public NotificationObject(Event o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public NotificationObject(Program o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public NotificationObject(Report o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public NotificationObject(Resource o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public NotificationObject(Subscription o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public NotificationObject(Ven o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("Event", Event.class);
        schemas.put("Program", Program.class);
        schemas.put("Report", Report.class);
        schemas.put("Resource", Resource.class);
        schemas.put("Subscription", Subscription.class);
        schemas.put("Ven", Ven.class);
        JSON.registerDescendants(NotificationObject.class, Collections.unmodifiableMap(schemas));
        // Initialize and register the discriminator mappings.
        Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
        mappings.put("event", Event.class);
        mappings.put("program", Program.class);
        mappings.put("report", Report.class);
        mappings.put("resource", Resource.class);
        mappings.put("subscription", Subscription.class);
        mappings.put("ven", Ven.class);
        mappings.put("notification_object", NotificationObject.class);
        JSON.registerDiscriminator(NotificationObject.class, "objectType", mappings);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return NotificationObject.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * Event, Program, Report, Resource, Subscription, Ven
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(Event.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(Program.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(Report.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(Resource.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(Subscription.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(Ven.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be Event, Program, Report, Resource, Subscription, Ven");
    }

    /**
     * Get the actual instance, which can be the following:
     * Event, Program, Report, Resource, Subscription, Ven
     *
     * @return The actual instance (Event, Program, Report, Resource, Subscription, Ven)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `Event`. If the actual instance is not `Event`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Event`
     * @throws ClassCastException if the instance is not `Event`
     */
    public Event getEvent() throws ClassCastException {
        return (Event)super.getActualInstance();
    }

    /**
     * Get the actual instance of `Program`. If the actual instance is not `Program`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Program`
     * @throws ClassCastException if the instance is not `Program`
     */
    public Program getProgram() throws ClassCastException {
        return (Program)super.getActualInstance();
    }

    /**
     * Get the actual instance of `Report`. If the actual instance is not `Report`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Report`
     * @throws ClassCastException if the instance is not `Report`
     */
    public Report getReport() throws ClassCastException {
        return (Report)super.getActualInstance();
    }

    /**
     * Get the actual instance of `Resource`. If the actual instance is not `Resource`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Resource`
     * @throws ClassCastException if the instance is not `Resource`
     */
    public Resource getResource() throws ClassCastException {
        return (Resource)super.getActualInstance();
    }

    /**
     * Get the actual instance of `Subscription`. If the actual instance is not `Subscription`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Subscription`
     * @throws ClassCastException if the instance is not `Subscription`
     */
    public Subscription getSubscription() throws ClassCastException {
        return (Subscription)super.getActualInstance();
    }

    /**
     * Get the actual instance of `Ven`. If the actual instance is not `Ven`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Ven`
     * @throws ClassCastException if the instance is not `Ven`
     */
    public Ven getVen() throws ClassCastException {
        return (Ven)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof Program) {
        if (getActualInstance() != null) {
          joiner.add(((Program)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof Report) {
        if (getActualInstance() != null) {
          joiner.add(((Report)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof Event) {
        if (getActualInstance() != null) {
          joiner.add(((Event)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof Subscription) {
        if (getActualInstance() != null) {
          joiner.add(((Subscription)getActualInstance()).toUrlQueryString(prefix + "one_of_3" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof Ven) {
        if (getActualInstance() != null) {
          joiner.add(((Ven)getActualInstance()).toUrlQueryString(prefix + "one_of_4" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof Resource) {
        if (getActualInstance() != null) {
          joiner.add(((Resource)getActualInstance()).toUrlQueryString(prefix + "one_of_5" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

