/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.clean_energy_tools.openadr_3_types.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


import io.github.clean_energy_tools.openadr_3_types.client.ApiClient;
/**
 * MQTT notifier topic names for notifications of subscribable-object operations
 */
@JsonPropertyOrder({
  NotifierOperationsTopics.JSON_PROPERTY_C_R_E_A_T_E,
  NotifierOperationsTopics.JSON_PROPERTY_U_P_D_A_T_E,
  NotifierOperationsTopics.JSON_PROPERTY_D_E_L_E_T_E,
  NotifierOperationsTopics.JSON_PROPERTY_A_L_L
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-23T09:35:23.176897405+03:00[Europe/Bucharest]", comments = "Generator version: 7.14.0")
public class NotifierOperationsTopics {
  public static final String JSON_PROPERTY_C_R_E_A_T_E = "CREATE";
  @javax.annotation.Nullable
  private String CREATE;

  public static final String JSON_PROPERTY_U_P_D_A_T_E = "UPDATE";
  @javax.annotation.Nonnull
  private String UPDATE;

  public static final String JSON_PROPERTY_D_E_L_E_T_E = "DELETE";
  @javax.annotation.Nonnull
  private String DELETE;

  public static final String JSON_PROPERTY_A_L_L = "ALL";
  @javax.annotation.Nullable
  private String ALL;

  public NotifierOperationsTopics() { 
  }

  public NotifierOperationsTopics CREATE(@javax.annotation.Nullable String CREATE) {
    this.CREATE = CREATE;
    return this;
  }

  /**
   * &#39;Topic path for CREATE operations,  not provided for notifications for a specific object ID,  e.g. until programID foo is created, clients unable to  request notifications of its creation&#39; 
   * @return CREATE
   */
  @javax.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_C_R_E_A_T_E)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCREATE() {
    return CREATE;
  }


  @JsonProperty(JSON_PROPERTY_C_R_E_A_T_E)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCREATE(@javax.annotation.Nullable String CREATE) {
    this.CREATE = CREATE;
  }


  public NotifierOperationsTopics UPDATE(@javax.annotation.Nonnull String UPDATE) {
    this.UPDATE = UPDATE;
    return this;
  }

  /**
   * Topic path for UPDATE operations
   * @return UPDATE
   */
  @javax.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_U_P_D_A_T_E)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUPDATE() {
    return UPDATE;
  }


  @JsonProperty(JSON_PROPERTY_U_P_D_A_T_E)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUPDATE(@javax.annotation.Nonnull String UPDATE) {
    this.UPDATE = UPDATE;
  }


  public NotifierOperationsTopics DELETE(@javax.annotation.Nonnull String DELETE) {
    this.DELETE = DELETE;
    return this;
  }

  /**
   * Topic path for DELETE operations
   * @return DELETE
   */
  @javax.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_D_E_L_E_T_E)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDELETE() {
    return DELETE;
  }


  @JsonProperty(JSON_PROPERTY_D_E_L_E_T_E)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDELETE(@javax.annotation.Nonnull String DELETE) {
    this.DELETE = DELETE;
  }


  public NotifierOperationsTopics ALL(@javax.annotation.Nullable String ALL) {
    this.ALL = ALL;
    return this;
  }

  /**
   * Topic path for ALL operations, if supported by VTN
   * @return ALL
   */
  @javax.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_A_L_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getALL() {
    return ALL;
  }


  @JsonProperty(JSON_PROPERTY_A_L_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setALL(@javax.annotation.Nullable String ALL) {
    this.ALL = ALL;
  }


  /**
   * Return true if this notifierOperationsTopics object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotifierOperationsTopics notifierOperationsTopics = (NotifierOperationsTopics) o;
    return Objects.equals(this.CREATE, notifierOperationsTopics.CREATE) &&
        Objects.equals(this.UPDATE, notifierOperationsTopics.UPDATE) &&
        Objects.equals(this.DELETE, notifierOperationsTopics.DELETE) &&
        Objects.equals(this.ALL, notifierOperationsTopics.ALL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(CREATE, UPDATE, DELETE, ALL);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotifierOperationsTopics {\n");
    sb.append("    CREATE: ").append(toIndentedString(CREATE)).append("\n");
    sb.append("    UPDATE: ").append(toIndentedString(UPDATE)).append("\n");
    sb.append("    DELETE: ").append(toIndentedString(DELETE)).append("\n");
    sb.append("    ALL: ").append(toIndentedString(ALL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `CREATE` to the URL query string
    if (getCREATE() != null) {
      joiner.add(String.format("%sCREATE%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCREATE()))));
    }

    // add `UPDATE` to the URL query string
    if (getUPDATE() != null) {
      joiner.add(String.format("%sUPDATE%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUPDATE()))));
    }

    // add `DELETE` to the URL query string
    if (getDELETE() != null) {
      joiner.add(String.format("%sDELETE%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDELETE()))));
    }

    // add `ALL` to the URL query string
    if (getALL() != null) {
      joiner.add(String.format("%sALL%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getALL()))));
    }

    return joiner.toString();
  }

    public static class Builder {

    private NotifierOperationsTopics instance;

    public Builder() {
      this(new NotifierOperationsTopics());
    }

    protected Builder(NotifierOperationsTopics instance) {
      this.instance = instance;
    }

    public NotifierOperationsTopics.Builder CREATE(String CREATE) {
      this.instance.CREATE = CREATE;
      return this;
    }
    public NotifierOperationsTopics.Builder UPDATE(String UPDATE) {
      this.instance.UPDATE = UPDATE;
      return this;
    }
    public NotifierOperationsTopics.Builder DELETE(String DELETE) {
      this.instance.DELETE = DELETE;
      return this;
    }
    public NotifierOperationsTopics.Builder ALL(String ALL) {
      this.instance.ALL = ALL;
      return this;
    }


    /**
    * returns a built NotifierOperationsTopics instance.
    *
    * The builder is not reusable.
    */
    public NotifierOperationsTopics build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static NotifierOperationsTopics.Builder builder() {
    return new NotifierOperationsTopics.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public NotifierOperationsTopics.Builder toBuilder() {
    return new NotifierOperationsTopics.Builder()
      .CREATE(getCREATE())
      .UPDATE(getUPDATE())
      .DELETE(getDELETE())
      .ALL(getALL());
  }

}

