/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.clean_energy_tools.openadr_3_types.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.clean_energy_tools.openadr_3_types.model.IntervalPeriod;
import io.github.clean_energy_tools.openadr_3_types.model.ProgramRequestPayloadDescriptorsInner;
import io.github.clean_energy_tools.openadr_3_types.model.ProgramRequestProgramDescriptionsInner;
import io.github.clean_energy_tools.openadr_3_types.model.ValuesMap;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


import io.github.clean_energy_tools.openadr_3_types.client.ApiClient;
/**
 * Client provided description of program
 */
@JsonPropertyOrder({
  ProgramRequest.JSON_PROPERTY_PROGRAM_NAME,
  ProgramRequest.JSON_PROPERTY_INTERVAL_PERIOD,
  ProgramRequest.JSON_PROPERTY_PROGRAM_DESCRIPTIONS,
  ProgramRequest.JSON_PROPERTY_PAYLOAD_DESCRIPTORS,
  ProgramRequest.JSON_PROPERTY_ATTRIBUTES,
  ProgramRequest.JSON_PROPERTY_TARGETS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-23T09:35:23.176897405+03:00[Europe/Bucharest]", comments = "Generator version: 7.14.0")
public class ProgramRequest {
  public static final String JSON_PROPERTY_PROGRAM_NAME = "programName";
  @javax.annotation.Nonnull
  private String programName;

  public static final String JSON_PROPERTY_INTERVAL_PERIOD = "intervalPeriod";
  @javax.annotation.Nullable
  private IntervalPeriod intervalPeriod;

  public static final String JSON_PROPERTY_PROGRAM_DESCRIPTIONS = "programDescriptions";
  private JsonNullable<List<@Valid ProgramRequestProgramDescriptionsInner>> programDescriptions = JsonNullable.<List<@Valid ProgramRequestProgramDescriptionsInner>>undefined();

  public static final String JSON_PROPERTY_PAYLOAD_DESCRIPTORS = "payloadDescriptors";
  private JsonNullable<List<ProgramRequestPayloadDescriptorsInner>> payloadDescriptors = JsonNullable.<List<ProgramRequestPayloadDescriptorsInner>>undefined();

  public static final String JSON_PROPERTY_ATTRIBUTES = "attributes";
  private JsonNullable<List<@Valid ValuesMap>> attributes = JsonNullable.<List<@Valid ValuesMap>>undefined();

  public static final String JSON_PROPERTY_TARGETS = "targets";
  private JsonNullable<List<@Size(min = 1, max = 128)String>> targets = JsonNullable.<List<@Size(min = 1, max = 128)String>>undefined();

  public ProgramRequest() { 
  }

  public ProgramRequest programName(@javax.annotation.Nonnull String programName) {
    this.programName = programName;
    return this;
  }

  /**
   * Short name to uniquely identify program.
   * @return programName
   */
  @javax.annotation.Nonnull
  @NotNull
 @Size(min=1,max=128)
  @JsonProperty(JSON_PROPERTY_PROGRAM_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getProgramName() {
    return programName;
  }


  @JsonProperty(JSON_PROPERTY_PROGRAM_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProgramName(@javax.annotation.Nonnull String programName) {
    this.programName = programName;
  }


  public ProgramRequest intervalPeriod(@javax.annotation.Nullable IntervalPeriod intervalPeriod) {
    this.intervalPeriod = intervalPeriod;
    return this;
  }

  /**
   * Get intervalPeriod
   * @return intervalPeriod
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_INTERVAL_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public IntervalPeriod getIntervalPeriod() {
    return intervalPeriod;
  }


  @JsonProperty(JSON_PROPERTY_INTERVAL_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIntervalPeriod(@javax.annotation.Nullable IntervalPeriod intervalPeriod) {
    this.intervalPeriod = intervalPeriod;
  }


  public ProgramRequest programDescriptions(@javax.annotation.Nullable List<@Valid ProgramRequestProgramDescriptionsInner> programDescriptions) {
    this.programDescriptions = JsonNullable.<List<@Valid ProgramRequestProgramDescriptionsInner>>of(programDescriptions);
    return this;
  }

  public ProgramRequest addProgramDescriptionsItem(ProgramRequestProgramDescriptionsInner programDescriptionsItem) {
    if (this.programDescriptions == null || !this.programDescriptions.isPresent()) {
      this.programDescriptions = JsonNullable.<List<@Valid ProgramRequestProgramDescriptionsInner>>of(new ArrayList<>());
    }
    try {
      this.programDescriptions.get().add(programDescriptionsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * A list of programDescriptions
   * @return programDescriptions
   */
  @javax.annotation.Nullable
  @Valid

  @JsonIgnore
  public List<@Valid ProgramRequestProgramDescriptionsInner> getProgramDescriptions() {
        return programDescriptions.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PROGRAM_DESCRIPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<@Valid ProgramRequestProgramDescriptionsInner>> getProgramDescriptions_JsonNullable() {
    return programDescriptions;
  }
  
  @JsonProperty(JSON_PROPERTY_PROGRAM_DESCRIPTIONS)
  public void setProgramDescriptions_JsonNullable(JsonNullable<List<@Valid ProgramRequestProgramDescriptionsInner>> programDescriptions) {
    this.programDescriptions = programDescriptions;
  }

  public void setProgramDescriptions(@javax.annotation.Nullable List<@Valid ProgramRequestProgramDescriptionsInner> programDescriptions) {
    this.programDescriptions = JsonNullable.<List<@Valid ProgramRequestProgramDescriptionsInner>>of(programDescriptions);
  }


  public ProgramRequest payloadDescriptors(@javax.annotation.Nullable List<ProgramRequestPayloadDescriptorsInner> payloadDescriptors) {
    this.payloadDescriptors = JsonNullable.<List<ProgramRequestPayloadDescriptorsInner>>of(payloadDescriptors);
    return this;
  }

  public ProgramRequest addPayloadDescriptorsItem(ProgramRequestPayloadDescriptorsInner payloadDescriptorsItem) {
    if (this.payloadDescriptors == null || !this.payloadDescriptors.isPresent()) {
      this.payloadDescriptors = JsonNullable.<List<ProgramRequestPayloadDescriptorsInner>>of(new ArrayList<>());
    }
    try {
      this.payloadDescriptors.get().add(payloadDescriptorsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * A list of payloadDescriptors.
   * @return payloadDescriptors
   */
  @javax.annotation.Nullable
  @Valid

  @JsonIgnore
  public List<ProgramRequestPayloadDescriptorsInner> getPayloadDescriptors() {
        return payloadDescriptors.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PAYLOAD_DESCRIPTORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<ProgramRequestPayloadDescriptorsInner>> getPayloadDescriptors_JsonNullable() {
    return payloadDescriptors;
  }
  
  @JsonProperty(JSON_PROPERTY_PAYLOAD_DESCRIPTORS)
  public void setPayloadDescriptors_JsonNullable(JsonNullable<List<ProgramRequestPayloadDescriptorsInner>> payloadDescriptors) {
    this.payloadDescriptors = payloadDescriptors;
  }

  public void setPayloadDescriptors(@javax.annotation.Nullable List<ProgramRequestPayloadDescriptorsInner> payloadDescriptors) {
    this.payloadDescriptors = JsonNullable.<List<ProgramRequestPayloadDescriptorsInner>>of(payloadDescriptors);
  }


  public ProgramRequest attributes(@javax.annotation.Nullable List<@Valid ValuesMap> attributes) {
    this.attributes = JsonNullable.<List<@Valid ValuesMap>>of(attributes);
    return this;
  }

  public ProgramRequest addAttributesItem(ValuesMap attributesItem) {
    if (this.attributes == null || !this.attributes.isPresent()) {
      this.attributes = JsonNullable.<List<@Valid ValuesMap>>of(new ArrayList<>());
    }
    try {
      this.attributes.get().add(attributesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * A list of valuesMap objects describing attributes.
   * @return attributes
   */
  @javax.annotation.Nullable
  @Valid

  @JsonIgnore
  public List<@Valid ValuesMap> getAttributes() {
        return attributes.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<@Valid ValuesMap>> getAttributes_JsonNullable() {
    return attributes;
  }
  
  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  public void setAttributes_JsonNullable(JsonNullable<List<@Valid ValuesMap>> attributes) {
    this.attributes = attributes;
  }

  public void setAttributes(@javax.annotation.Nullable List<@Valid ValuesMap> attributes) {
    this.attributes = JsonNullable.<List<@Valid ValuesMap>>of(attributes);
  }


  public ProgramRequest targets(@javax.annotation.Nullable List<@Size(min = 1, max = 128)String> targets) {
    this.targets = JsonNullable.<List<@Size(min = 1, max = 128)String>>of(targets);
    return this;
  }

  public ProgramRequest addTargetsItem(String targetsItem) {
    if (this.targets == null || !this.targets.isPresent()) {
      this.targets = JsonNullable.<List<@Size(min = 1, max = 128)String>>of(new ArrayList<>());
    }
    try {
      this.targets.get().add(targetsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * A list of targets.
   * @return targets
   */
  @javax.annotation.Nullable

  @JsonIgnore
  public List<@Size(min = 1, max = 128)String> getTargets() {
        return targets.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TARGETS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<@Size(min = 1, max = 128)String>> getTargets_JsonNullable() {
    return targets;
  }
  
  @JsonProperty(JSON_PROPERTY_TARGETS)
  public void setTargets_JsonNullable(JsonNullable<List<@Size(min = 1, max = 128)String>> targets) {
    this.targets = targets;
  }

  public void setTargets(@javax.annotation.Nullable List<@Size(min = 1, max = 128)String> targets) {
    this.targets = JsonNullable.<List<@Size(min = 1, max = 128)String>>of(targets);
  }


  /**
   * Return true if this programRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProgramRequest programRequest = (ProgramRequest) o;
    return Objects.equals(this.programName, programRequest.programName) &&
        Objects.equals(this.intervalPeriod, programRequest.intervalPeriod) &&
        equalsNullable(this.programDescriptions, programRequest.programDescriptions) &&
        equalsNullable(this.payloadDescriptors, programRequest.payloadDescriptors) &&
        equalsNullable(this.attributes, programRequest.attributes) &&
        equalsNullable(this.targets, programRequest.targets);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(programName, intervalPeriod, hashCodeNullable(programDescriptions), hashCodeNullable(payloadDescriptors), hashCodeNullable(attributes), hashCodeNullable(targets));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProgramRequest {\n");
    sb.append("    programName: ").append(toIndentedString(programName)).append("\n");
    sb.append("    intervalPeriod: ").append(toIndentedString(intervalPeriod)).append("\n");
    sb.append("    programDescriptions: ").append(toIndentedString(programDescriptions)).append("\n");
    sb.append("    payloadDescriptors: ").append(toIndentedString(payloadDescriptors)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    targets: ").append(toIndentedString(targets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `programName` to the URL query string
    if (getProgramName() != null) {
      joiner.add(String.format("%sprogramName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProgramName()))));
    }

    // add `intervalPeriod` to the URL query string
    if (getIntervalPeriod() != null) {
      joiner.add(getIntervalPeriod().toUrlQueryString(prefix + "intervalPeriod" + suffix));
    }

    // add `programDescriptions` to the URL query string
    if (getProgramDescriptions() != null) {
      for (int i = 0; i < getProgramDescriptions().size(); i++) {
        if (getProgramDescriptions().get(i) != null) {
          joiner.add(getProgramDescriptions().get(i).toUrlQueryString(String.format("%sprogramDescriptions%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `payloadDescriptors` to the URL query string
    if (getPayloadDescriptors() != null) {
      for (int i = 0; i < getPayloadDescriptors().size(); i++) {
        if (getPayloadDescriptors().get(i) != null) {
          joiner.add(getPayloadDescriptors().get(i).toUrlQueryString(String.format("%spayloadDescriptors%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `attributes` to the URL query string
    if (getAttributes() != null) {
      for (int i = 0; i < getAttributes().size(); i++) {
        if (getAttributes().get(i) != null) {
          joiner.add(getAttributes().get(i).toUrlQueryString(String.format("%sattributes%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `targets` to the URL query string
    if (getTargets() != null) {
      for (int i = 0; i < getTargets().size(); i++) {
        joiner.add(String.format("%stargets%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getTargets().get(i)))));
      }
    }

    return joiner.toString();
  }

    public static class Builder {

    private ProgramRequest instance;

    public Builder() {
      this(new ProgramRequest());
    }

    protected Builder(ProgramRequest instance) {
      this.instance = instance;
    }

    public ProgramRequest.Builder programName(String programName) {
      this.instance.programName = programName;
      return this;
    }
    public ProgramRequest.Builder intervalPeriod(IntervalPeriod intervalPeriod) {
      this.instance.intervalPeriod = intervalPeriod;
      return this;
    }
    public ProgramRequest.Builder programDescriptions(List<ProgramRequestProgramDescriptionsInner> programDescriptions) {
      this.instance.programDescriptions = JsonNullable.<List<ProgramRequestProgramDescriptionsInner>>of(programDescriptions);
      return this;
    }
    public ProgramRequest.Builder programDescriptions(JsonNullable<List<ProgramRequestProgramDescriptionsInner>> programDescriptions) {
      this.instance.programDescriptions = programDescriptions;
      return this;
    }
    public ProgramRequest.Builder payloadDescriptors(List<ProgramRequestPayloadDescriptorsInner> payloadDescriptors) {
      this.instance.payloadDescriptors = JsonNullable.<List<ProgramRequestPayloadDescriptorsInner>>of(payloadDescriptors);
      return this;
    }
    public ProgramRequest.Builder payloadDescriptors(JsonNullable<List<ProgramRequestPayloadDescriptorsInner>> payloadDescriptors) {
      this.instance.payloadDescriptors = payloadDescriptors;
      return this;
    }
    public ProgramRequest.Builder attributes(List<ValuesMap> attributes) {
      this.instance.attributes = JsonNullable.<List<ValuesMap>>of(attributes);
      return this;
    }
    public ProgramRequest.Builder attributes(JsonNullable<List<ValuesMap>> attributes) {
      this.instance.attributes = attributes;
      return this;
    }
    public ProgramRequest.Builder targets(List<String> targets) {
      this.instance.targets = JsonNullable.<List<String>>of(targets);
      return this;
    }
    public ProgramRequest.Builder targets(JsonNullable<List<String>> targets) {
      this.instance.targets = targets;
      return this;
    }


    /**
    * returns a built ProgramRequest instance.
    *
    * The builder is not reusable.
    */
    public ProgramRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ProgramRequest.Builder builder() {
    return new ProgramRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ProgramRequest.Builder toBuilder() {
    return new ProgramRequest.Builder()
      .programName(getProgramName())
      .intervalPeriod(getIntervalPeriod())
      .programDescriptions(getProgramDescriptions())
      .payloadDescriptors(getPayloadDescriptors())
      .attributes(getAttributes())
      .targets(getTargets());
  }

}

