/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.clean_energy_tools.openadr_3_types.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.clean_energy_tools.openadr_3_types.model.Interval;
import io.github.clean_energy_tools.openadr_3_types.model.IntervalPeriod;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


import io.github.clean_energy_tools.openadr_3_types.client.ApiClient;
/**
 * Report data associated with a resource.
 */
@JsonPropertyOrder({
  ReportRequestResourcesInner.JSON_PROPERTY_RESOURCE_NAME,
  ReportRequestResourcesInner.JSON_PROPERTY_INTERVAL_PERIOD,
  ReportRequestResourcesInner.JSON_PROPERTY_INTERVALS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-23T09:35:23.176897405+03:00[Europe/Bucharest]", comments = "Generator version: 7.14.0")
public class ReportRequestResourcesInner {
  public static final String JSON_PROPERTY_RESOURCE_NAME = "resourceName";
  @javax.annotation.Nonnull
  private String resourceName;

  public static final String JSON_PROPERTY_INTERVAL_PERIOD = "intervalPeriod";
  @javax.annotation.Nullable
  private IntervalPeriod intervalPeriod;

  public static final String JSON_PROPERTY_INTERVALS = "intervals";
  @javax.annotation.Nonnull
  private List<@Valid Interval> intervals = new ArrayList<>();

  public ReportRequestResourcesInner() { 
  }

  public ReportRequestResourcesInner resourceName(@javax.annotation.Nonnull String resourceName) {
    this.resourceName = resourceName;
    return this;
  }

  /**
   * User generated identifier. A value of AGGREGATED_REPORT indicates an aggregation of more that one resource&#39;s data
   * @return resourceName
   */
  @javax.annotation.Nonnull
  @NotNull
 @Size(min=1,max=128)
  @JsonProperty(JSON_PROPERTY_RESOURCE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getResourceName() {
    return resourceName;
  }


  @JsonProperty(JSON_PROPERTY_RESOURCE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResourceName(@javax.annotation.Nonnull String resourceName) {
    this.resourceName = resourceName;
  }


  public ReportRequestResourcesInner intervalPeriod(@javax.annotation.Nullable IntervalPeriod intervalPeriod) {
    this.intervalPeriod = intervalPeriod;
    return this;
  }

  /**
   * Get intervalPeriod
   * @return intervalPeriod
   */
  @javax.annotation.Nullable
  @Valid

  @JsonProperty(JSON_PROPERTY_INTERVAL_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public IntervalPeriod getIntervalPeriod() {
    return intervalPeriod;
  }


  @JsonProperty(JSON_PROPERTY_INTERVAL_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIntervalPeriod(@javax.annotation.Nullable IntervalPeriod intervalPeriod) {
    this.intervalPeriod = intervalPeriod;
  }


  public ReportRequestResourcesInner intervals(@javax.annotation.Nonnull List<@Valid Interval> intervals) {
    this.intervals = intervals;
    return this;
  }

  public ReportRequestResourcesInner addIntervalsItem(Interval intervalsItem) {
    if (this.intervals == null) {
      this.intervals = new ArrayList<>();
    }
    this.intervals.add(intervalsItem);
    return this;
  }

  /**
   * A list of interval objects.
   * @return intervals
   */
  @javax.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_INTERVALS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<@Valid Interval> getIntervals() {
    return intervals;
  }


  @JsonProperty(JSON_PROPERTY_INTERVALS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIntervals(@javax.annotation.Nonnull List<@Valid Interval> intervals) {
    this.intervals = intervals;
  }


  /**
   * Return true if this reportRequest_resources_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportRequestResourcesInner reportRequestResourcesInner = (ReportRequestResourcesInner) o;
    return Objects.equals(this.resourceName, reportRequestResourcesInner.resourceName) &&
        Objects.equals(this.intervalPeriod, reportRequestResourcesInner.intervalPeriod) &&
        Objects.equals(this.intervals, reportRequestResourcesInner.intervals);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceName, intervalPeriod, intervals);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportRequestResourcesInner {\n");
    sb.append("    resourceName: ").append(toIndentedString(resourceName)).append("\n");
    sb.append("    intervalPeriod: ").append(toIndentedString(intervalPeriod)).append("\n");
    sb.append("    intervals: ").append(toIndentedString(intervals)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `resourceName` to the URL query string
    if (getResourceName() != null) {
      joiner.add(String.format("%sresourceName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResourceName()))));
    }

    // add `intervalPeriod` to the URL query string
    if (getIntervalPeriod() != null) {
      joiner.add(getIntervalPeriod().toUrlQueryString(prefix + "intervalPeriod" + suffix));
    }

    // add `intervals` to the URL query string
    if (getIntervals() != null) {
      for (int i = 0; i < getIntervals().size(); i++) {
        if (getIntervals().get(i) != null) {
          joiner.add(getIntervals().get(i).toUrlQueryString(String.format("%sintervals%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

    public static class Builder {

    private ReportRequestResourcesInner instance;

    public Builder() {
      this(new ReportRequestResourcesInner());
    }

    protected Builder(ReportRequestResourcesInner instance) {
      this.instance = instance;
    }

    public ReportRequestResourcesInner.Builder resourceName(String resourceName) {
      this.instance.resourceName = resourceName;
      return this;
    }
    public ReportRequestResourcesInner.Builder intervalPeriod(IntervalPeriod intervalPeriod) {
      this.instance.intervalPeriod = intervalPeriod;
      return this;
    }
    public ReportRequestResourcesInner.Builder intervals(List<Interval> intervals) {
      this.instance.intervals = intervals;
      return this;
    }


    /**
    * returns a built ReportRequestResourcesInner instance.
    *
    * The builder is not reusable.
    */
    public ReportRequestResourcesInner build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static ReportRequestResourcesInner.Builder builder() {
    return new ReportRequestResourcesInner.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public ReportRequestResourcesInner.Builder toBuilder() {
    return new ReportRequestResourcesInner.Builder()
      .resourceName(getResourceName())
      .intervalPeriod(getIntervalPeriod())
      .intervals(getIntervals());
  }

}

