/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.clean_energy_tools.openadr_3_types.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.clean_energy_tools.openadr_3_types.model.ValuesMap;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


import io.github.clean_energy_tools.openadr_3_types.client.ApiClient;
/**
 * Server provided representation of resource
 */
@JsonPropertyOrder({
  Resource.JSON_PROPERTY_ID,
  Resource.JSON_PROPERTY_CREATED_DATE_TIME,
  Resource.JSON_PROPERTY_MODIFICATION_DATE_TIME,
  Resource.JSON_PROPERTY_OBJECT_TYPE,
  Resource.JSON_PROPERTY_CLIENT_I_D,
  Resource.JSON_PROPERTY_TARGETS,
  Resource.JSON_PROPERTY_RESOURCE_NAME,
  Resource.JSON_PROPERTY_VEN_I_D,
  Resource.JSON_PROPERTY_ATTRIBUTES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-23T09:35:23.176897405+03:00[Europe/Bucharest]", comments = "Generator version: 7.14.0")
public class Resource {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_CREATED_DATE_TIME = "createdDateTime";
  @javax.annotation.Nonnull
  private OffsetDateTime createdDateTime;

  public static final String JSON_PROPERTY_MODIFICATION_DATE_TIME = "modificationDateTime";
  @javax.annotation.Nonnull
  private OffsetDateTime modificationDateTime;

  /**
   * Used as discriminator.
   */
  public enum ObjectTypeEnum {
    BL_RESOURCE_REQUEST(String.valueOf("BL_RESOURCE_REQUEST"));

    private String value;

    ObjectTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ObjectTypeEnum fromValue(String value) {
      for (ObjectTypeEnum b : ObjectTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OBJECT_TYPE = "objectType";
  @javax.annotation.Nonnull
  private ObjectTypeEnum objectType;

  public static final String JSON_PROPERTY_CLIENT_I_D = "clientID";
  @javax.annotation.Nonnull
  private String clientID;

  public static final String JSON_PROPERTY_TARGETS = "targets";
  private JsonNullable<List<@Size(min = 1, max = 128)String>> targets = JsonNullable.<List<@Size(min = 1, max = 128)String>>undefined();

  public static final String JSON_PROPERTY_RESOURCE_NAME = "resourceName";
  @javax.annotation.Nonnull
  private String resourceName;

  public static final String JSON_PROPERTY_VEN_I_D = "venID";
  @javax.annotation.Nonnull
  private String venID;

  public static final String JSON_PROPERTY_ATTRIBUTES = "attributes";
  private JsonNullable<List<@Valid ValuesMap>> attributes = JsonNullable.<List<@Valid ValuesMap>>undefined();

  public Resource() { 
  }

  public Resource id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * URL safe VTN assigned object ID.
   * @return id
   */
  @javax.annotation.Nonnull
  @NotNull
 @Pattern(regexp="^[a-zA-Z0-9_-]*$") @Size(min=1,max=128)
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public Resource createdDateTime(@javax.annotation.Nonnull OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

  /**
   * datetime in RFC 3339 format
   * @return createdDateTime
   */
  @javax.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_CREATED_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getCreatedDateTime() {
    return createdDateTime;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedDateTime(@javax.annotation.Nonnull OffsetDateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }


  public Resource modificationDateTime(@javax.annotation.Nonnull OffsetDateTime modificationDateTime) {
    this.modificationDateTime = modificationDateTime;
    return this;
  }

  /**
   * datetime in RFC 3339 format
   * @return modificationDateTime
   */
  @javax.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_MODIFICATION_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getModificationDateTime() {
    return modificationDateTime;
  }


  @JsonProperty(JSON_PROPERTY_MODIFICATION_DATE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModificationDateTime(@javax.annotation.Nonnull OffsetDateTime modificationDateTime) {
    this.modificationDateTime = modificationDateTime;
  }


  public Resource objectType(@javax.annotation.Nonnull ObjectTypeEnum objectType) {
    this.objectType = objectType;
    return this;
  }

  /**
   * Used as discriminator.
   * @return objectType
   */
  @javax.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_OBJECT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ObjectTypeEnum getObjectType() {
    return objectType;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObjectType(@javax.annotation.Nonnull ObjectTypeEnum objectType) {
    this.objectType = objectType;
  }


  public Resource clientID(@javax.annotation.Nonnull String clientID) {
    this.clientID = clientID;
    return this;
  }

  /**
   * ClientID as provisioned by Auhtentication Service and associated with client&#39;s bearer token 
   * @return clientID
   */
  @javax.annotation.Nonnull
  @NotNull
 @Size(min=1,max=128)
  @JsonProperty(JSON_PROPERTY_CLIENT_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getClientID() {
    return clientID;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientID(@javax.annotation.Nonnull String clientID) {
    this.clientID = clientID;
  }


  public Resource targets(@javax.annotation.Nullable List<@Size(min = 1, max = 128)String> targets) {
    this.targets = JsonNullable.<List<@Size(min = 1, max = 128)String>>of(targets);
    return this;
  }

  public Resource addTargetsItem(String targetsItem) {
    if (this.targets == null || !this.targets.isPresent()) {
      this.targets = JsonNullable.<List<@Size(min = 1, max = 128)String>>of(new ArrayList<>());
    }
    try {
      this.targets.get().add(targetsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * A list of targets.
   * @return targets
   */
  @javax.annotation.Nullable

  @JsonIgnore
  public List<@Size(min = 1, max = 128)String> getTargets() {
        return targets.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TARGETS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<@Size(min = 1, max = 128)String>> getTargets_JsonNullable() {
    return targets;
  }
  
  @JsonProperty(JSON_PROPERTY_TARGETS)
  public void setTargets_JsonNullable(JsonNullable<List<@Size(min = 1, max = 128)String>> targets) {
    this.targets = targets;
  }

  public void setTargets(@javax.annotation.Nullable List<@Size(min = 1, max = 128)String> targets) {
    this.targets = JsonNullable.<List<@Size(min = 1, max = 128)String>>of(targets);
  }


  public Resource resourceName(@javax.annotation.Nonnull String resourceName) {
    this.resourceName = resourceName;
    return this;
  }

  /**
   * User generated identifier. A value of AGGREGATED_REPORT indicates an aggregation of more that one resource&#39;s data
   * @return resourceName
   */
  @javax.annotation.Nonnull
  @NotNull
 @Size(min=1,max=128)
  @JsonProperty(JSON_PROPERTY_RESOURCE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getResourceName() {
    return resourceName;
  }


  @JsonProperty(JSON_PROPERTY_RESOURCE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResourceName(@javax.annotation.Nonnull String resourceName) {
    this.resourceName = resourceName;
  }


  public Resource venID(@javax.annotation.Nonnull String venID) {
    this.venID = venID;
    return this;
  }

  /**
   * URL safe VTN assigned object ID.
   * @return venID
   */
  @javax.annotation.Nonnull
  @NotNull
 @Pattern(regexp="^[a-zA-Z0-9_-]*$") @Size(min=1,max=128)
  @JsonProperty(JSON_PROPERTY_VEN_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getVenID() {
    return venID;
  }


  @JsonProperty(JSON_PROPERTY_VEN_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVenID(@javax.annotation.Nonnull String venID) {
    this.venID = venID;
  }


  public Resource attributes(@javax.annotation.Nullable List<@Valid ValuesMap> attributes) {
    this.attributes = JsonNullable.<List<@Valid ValuesMap>>of(attributes);
    return this;
  }

  public Resource addAttributesItem(ValuesMap attributesItem) {
    if (this.attributes == null || !this.attributes.isPresent()) {
      this.attributes = JsonNullable.<List<@Valid ValuesMap>>of(new ArrayList<>());
    }
    try {
      this.attributes.get().add(attributesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * A list of valuesMap objects describing attributes.
   * @return attributes
   */
  @javax.annotation.Nullable
  @Valid

  @JsonIgnore
  public List<@Valid ValuesMap> getAttributes() {
        return attributes.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<@Valid ValuesMap>> getAttributes_JsonNullable() {
    return attributes;
  }
  
  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  public void setAttributes_JsonNullable(JsonNullable<List<@Valid ValuesMap>> attributes) {
    this.attributes = attributes;
  }

  public void setAttributes(@javax.annotation.Nullable List<@Valid ValuesMap> attributes) {
    this.attributes = JsonNullable.<List<@Valid ValuesMap>>of(attributes);
  }


  /**
   * Return true if this resource object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Resource resource = (Resource) o;
    return Objects.equals(this.id, resource.id) &&
        Objects.equals(this.createdDateTime, resource.createdDateTime) &&
        Objects.equals(this.modificationDateTime, resource.modificationDateTime) &&
        Objects.equals(this.objectType, resource.objectType) &&
        Objects.equals(this.clientID, resource.clientID) &&
        equalsNullable(this.targets, resource.targets) &&
        Objects.equals(this.resourceName, resource.resourceName) &&
        Objects.equals(this.venID, resource.venID) &&
        equalsNullable(this.attributes, resource.attributes);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdDateTime, modificationDateTime, objectType, clientID, hashCodeNullable(targets), resourceName, venID, hashCodeNullable(attributes));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Resource {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    modificationDateTime: ").append(toIndentedString(modificationDateTime)).append("\n");
    sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
    sb.append("    clientID: ").append(toIndentedString(clientID)).append("\n");
    sb.append("    targets: ").append(toIndentedString(targets)).append("\n");
    sb.append("    resourceName: ").append(toIndentedString(resourceName)).append("\n");
    sb.append("    venID: ").append(toIndentedString(venID)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `createdDateTime` to the URL query string
    if (getCreatedDateTime() != null) {
      joiner.add(String.format("%screatedDateTime%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedDateTime()))));
    }

    // add `modificationDateTime` to the URL query string
    if (getModificationDateTime() != null) {
      joiner.add(String.format("%smodificationDateTime%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getModificationDateTime()))));
    }

    // add `objectType` to the URL query string
    if (getObjectType() != null) {
      joiner.add(String.format("%sobjectType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getObjectType()))));
    }

    // add `clientID` to the URL query string
    if (getClientID() != null) {
      joiner.add(String.format("%sclientID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getClientID()))));
    }

    // add `targets` to the URL query string
    if (getTargets() != null) {
      for (int i = 0; i < getTargets().size(); i++) {
        joiner.add(String.format("%stargets%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getTargets().get(i)))));
      }
    }

    // add `resourceName` to the URL query string
    if (getResourceName() != null) {
      joiner.add(String.format("%sresourceName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResourceName()))));
    }

    // add `venID` to the URL query string
    if (getVenID() != null) {
      joiner.add(String.format("%svenID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVenID()))));
    }

    // add `attributes` to the URL query string
    if (getAttributes() != null) {
      for (int i = 0; i < getAttributes().size(); i++) {
        if (getAttributes().get(i) != null) {
          joiner.add(getAttributes().get(i).toUrlQueryString(String.format("%sattributes%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

    public static class Builder {

    private Resource instance;

    public Builder() {
      this(new Resource());
    }

    protected Builder(Resource instance) {
      this.instance = instance;
    }

    public Resource.Builder id(String id) {
      this.instance.id = id;
      return this;
    }
    public Resource.Builder createdDateTime(OffsetDateTime createdDateTime) {
      this.instance.createdDateTime = createdDateTime;
      return this;
    }
    public Resource.Builder modificationDateTime(OffsetDateTime modificationDateTime) {
      this.instance.modificationDateTime = modificationDateTime;
      return this;
    }
    public Resource.Builder objectType(ObjectTypeEnum objectType) {
      this.instance.objectType = objectType;
      return this;
    }
    public Resource.Builder clientID(String clientID) {
      this.instance.clientID = clientID;
      return this;
    }
    public Resource.Builder targets(List<String> targets) {
      this.instance.targets = JsonNullable.<List<String>>of(targets);
      return this;
    }
    public Resource.Builder targets(JsonNullable<List<String>> targets) {
      this.instance.targets = targets;
      return this;
    }
    public Resource.Builder resourceName(String resourceName) {
      this.instance.resourceName = resourceName;
      return this;
    }
    public Resource.Builder venID(String venID) {
      this.instance.venID = venID;
      return this;
    }
    public Resource.Builder attributes(List<ValuesMap> attributes) {
      this.instance.attributes = JsonNullable.<List<ValuesMap>>of(attributes);
      return this;
    }
    public Resource.Builder attributes(JsonNullable<List<ValuesMap>> attributes) {
      this.instance.attributes = attributes;
      return this;
    }


    /**
    * returns a built Resource instance.
    *
    * The builder is not reusable.
    */
    public Resource build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static Resource.Builder builder() {
    return new Resource.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public Resource.Builder toBuilder() {
    return new Resource.Builder()
      .id(getId())
      .createdDateTime(getCreatedDateTime())
      .modificationDateTime(getModificationDateTime())
      .objectType(getObjectType())
      .clientID(getClientID())
      .targets(getTargets())
      .resourceName(getResourceName())
      .venID(getVenID())
      .attributes(getAttributes());
  }

}

