/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.clean_energy_tools.openadr_3_types.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.clean_energy_tools.openadr_3_types.model.ObjectTypes;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


import io.github.clean_energy_tools.openadr_3_types.client.ApiClient;
/**
 * object type, operations, and callbackUrl.
 */
@JsonPropertyOrder({
  SubscriptionRequestObjectOperationsInner.JSON_PROPERTY_OBJECTS,
  SubscriptionRequestObjectOperationsInner.JSON_PROPERTY_OPERATIONS,
  SubscriptionRequestObjectOperationsInner.JSON_PROPERTY_CALLBACK_URL,
  SubscriptionRequestObjectOperationsInner.JSON_PROPERTY_BEARER_TOKEN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-23T09:35:23.176897405+03:00[Europe/Bucharest]", comments = "Generator version: 7.14.0")
public class SubscriptionRequestObjectOperationsInner {
  public static final String JSON_PROPERTY_OBJECTS = "objects";
  @javax.annotation.Nonnull
  private List<ObjectTypes> objects = new ArrayList<>();

  /**
   * object operation to subscribe to.
   */
  public enum OperationsEnum {
    READ(String.valueOf("READ")),
    
    CREATE(String.valueOf("CREATE")),
    
    UPDATE(String.valueOf("UPDATE")),
    
    DELETE(String.valueOf("DELETE"));

    private String value;

    OperationsEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OperationsEnum fromValue(String value) {
      for (OperationsEnum b : OperationsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OPERATIONS = "operations";
  @javax.annotation.Nonnull
  private List<OperationsEnum> operations = new ArrayList<>();

  public static final String JSON_PROPERTY_CALLBACK_URL = "callbackUrl";
  @javax.annotation.Nonnull
  private URI callbackUrl;

  public static final String JSON_PROPERTY_BEARER_TOKEN = "bearerToken";
  private JsonNullable<String> bearerToken = JsonNullable.<String>undefined();

  public SubscriptionRequestObjectOperationsInner() { 
  }

  public SubscriptionRequestObjectOperationsInner objects(@javax.annotation.Nonnull List<ObjectTypes> objects) {
    this.objects = objects;
    return this;
  }

  public SubscriptionRequestObjectOperationsInner addObjectsItem(ObjectTypes objectsItem) {
    if (this.objects == null) {
      this.objects = new ArrayList<>();
    }
    this.objects.add(objectsItem);
    return this;
  }

  /**
   * list of objects to subscribe to.
   * @return objects
   */
  @javax.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_OBJECTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<ObjectTypes> getObjects() {
    return objects;
  }


  @JsonProperty(JSON_PROPERTY_OBJECTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObjects(@javax.annotation.Nonnull List<ObjectTypes> objects) {
    this.objects = objects;
  }


  public SubscriptionRequestObjectOperationsInner operations(@javax.annotation.Nonnull List<OperationsEnum> operations) {
    this.operations = operations;
    return this;
  }

  public SubscriptionRequestObjectOperationsInner addOperationsItem(OperationsEnum operationsItem) {
    if (this.operations == null) {
      this.operations = new ArrayList<>();
    }
    this.operations.add(operationsItem);
    return this;
  }

  /**
   * list of operations to subscribe to.
   * @return operations
   */
  @javax.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_OPERATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<OperationsEnum> getOperations() {
    return operations;
  }


  @JsonProperty(JSON_PROPERTY_OPERATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOperations(@javax.annotation.Nonnull List<OperationsEnum> operations) {
    this.operations = operations;
  }


  public SubscriptionRequestObjectOperationsInner callbackUrl(@javax.annotation.Nonnull URI callbackUrl) {
    this.callbackUrl = callbackUrl;
    return this;
  }

  /**
   * User provided webhook URL.
   * @return callbackUrl
   */
  @javax.annotation.Nonnull
  @NotNull
  @Valid
 @Size(min=2,max=8000)
  @JsonProperty(JSON_PROPERTY_CALLBACK_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public URI getCallbackUrl() {
    return callbackUrl;
  }


  @JsonProperty(JSON_PROPERTY_CALLBACK_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCallbackUrl(@javax.annotation.Nonnull URI callbackUrl) {
    this.callbackUrl = callbackUrl;
  }


  public SubscriptionRequestObjectOperationsInner bearerToken(@javax.annotation.Nullable String bearerToken) {
    this.bearerToken = JsonNullable.<String>of(bearerToken);
    return this;
  }

  /**
   * User provided token. To avoid custom integrations, callback endpoints should accept the provided bearer token to authenticate VTN requests. 
   * @return bearerToken
   */
  @javax.annotation.Nullable

  @JsonIgnore
  public String getBearerToken() {
        return bearerToken.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_BEARER_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getBearerToken_JsonNullable() {
    return bearerToken;
  }
  
  @JsonProperty(JSON_PROPERTY_BEARER_TOKEN)
  public void setBearerToken_JsonNullable(JsonNullable<String> bearerToken) {
    this.bearerToken = bearerToken;
  }

  public void setBearerToken(@javax.annotation.Nullable String bearerToken) {
    this.bearerToken = JsonNullable.<String>of(bearerToken);
  }


  /**
   * Return true if this subscriptionRequest_objectOperations_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionRequestObjectOperationsInner subscriptionRequestObjectOperationsInner = (SubscriptionRequestObjectOperationsInner) o;
    return Objects.equals(this.objects, subscriptionRequestObjectOperationsInner.objects) &&
        Objects.equals(this.operations, subscriptionRequestObjectOperationsInner.operations) &&
        Objects.equals(this.callbackUrl, subscriptionRequestObjectOperationsInner.callbackUrl) &&
        equalsNullable(this.bearerToken, subscriptionRequestObjectOperationsInner.bearerToken);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(objects, operations, callbackUrl, hashCodeNullable(bearerToken));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionRequestObjectOperationsInner {\n");
    sb.append("    objects: ").append(toIndentedString(objects)).append("\n");
    sb.append("    operations: ").append(toIndentedString(operations)).append("\n");
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    bearerToken: ").append(toIndentedString(bearerToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `objects` to the URL query string
    if (getObjects() != null) {
      for (int i = 0; i < getObjects().size(); i++) {
        if (getObjects().get(i) != null) {
          joiner.add(String.format("%sobjects%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
              ApiClient.urlEncode(ApiClient.valueToString(getObjects().get(i)))));
        }
      }
    }

    // add `operations` to the URL query string
    if (getOperations() != null) {
      for (int i = 0; i < getOperations().size(); i++) {
        joiner.add(String.format("%soperations%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getOperations().get(i)))));
      }
    }

    // add `callbackUrl` to the URL query string
    if (getCallbackUrl() != null) {
      joiner.add(String.format("%scallbackUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCallbackUrl()))));
    }

    // add `bearerToken` to the URL query string
    if (getBearerToken() != null) {
      joiner.add(String.format("%sbearerToken%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBearerToken()))));
    }

    return joiner.toString();
  }

    public static class Builder {

    private SubscriptionRequestObjectOperationsInner instance;

    public Builder() {
      this(new SubscriptionRequestObjectOperationsInner());
    }

    protected Builder(SubscriptionRequestObjectOperationsInner instance) {
      this.instance = instance;
    }

    public SubscriptionRequestObjectOperationsInner.Builder objects(List<ObjectTypes> objects) {
      this.instance.objects = objects;
      return this;
    }
    public SubscriptionRequestObjectOperationsInner.Builder operations(List<OperationsEnum> operations) {
      this.instance.operations = operations;
      return this;
    }
    public SubscriptionRequestObjectOperationsInner.Builder callbackUrl(URI callbackUrl) {
      this.instance.callbackUrl = callbackUrl;
      return this;
    }
    public SubscriptionRequestObjectOperationsInner.Builder bearerToken(String bearerToken) {
      this.instance.bearerToken = JsonNullable.<String>of(bearerToken);
      return this;
    }
    public SubscriptionRequestObjectOperationsInner.Builder bearerToken(JsonNullable<String> bearerToken) {
      this.instance.bearerToken = bearerToken;
      return this;
    }


    /**
    * returns a built SubscriptionRequestObjectOperationsInner instance.
    *
    * The builder is not reusable.
    */
    public SubscriptionRequestObjectOperationsInner build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static SubscriptionRequestObjectOperationsInner.Builder builder() {
    return new SubscriptionRequestObjectOperationsInner.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public SubscriptionRequestObjectOperationsInner.Builder toBuilder() {
    return new SubscriptionRequestObjectOperationsInner.Builder()
      .objects(getObjects())
      .operations(getOperations())
      .callbackUrl(getCallbackUrl())
      .bearerToken(getBearerToken());
  }

}

