/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.clean_energy_tools.openadr_3_types.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.clean_energy_tools.openadr_3_types.model.SubscriptionRequestObjectOperationsInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


import io.github.clean_energy_tools.openadr_3_types.client.ApiClient;
/**
 * An object created by a client to receive notification of operations on objects. Clients may subscribe to be notified when a type of object is created, updated, or deleted. 
 */
@JsonPropertyOrder({
  SubscriptionRequest.JSON_PROPERTY_CLIENT_NAME,
  SubscriptionRequest.JSON_PROPERTY_PROGRAM_I_D,
  SubscriptionRequest.JSON_PROPERTY_OBJECT_OPERATIONS,
  SubscriptionRequest.JSON_PROPERTY_TARGETS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-23T09:35:23.176897405+03:00[Europe/Bucharest]", comments = "Generator version: 7.14.0")
public class SubscriptionRequest {
  public static final String JSON_PROPERTY_CLIENT_NAME = "clientName";
  @javax.annotation.Nonnull
  private String clientName;

  public static final String JSON_PROPERTY_PROGRAM_I_D = "programID";
  @javax.annotation.Nullable
  private String programID;

  public static final String JSON_PROPERTY_OBJECT_OPERATIONS = "objectOperations";
  @javax.annotation.Nonnull
  private List<@Valid SubscriptionRequestObjectOperationsInner> objectOperations = new ArrayList<>();

  public static final String JSON_PROPERTY_TARGETS = "targets";
  private JsonNullable<List<@Size(min = 1, max = 128)String>> targets = JsonNullable.<List<@Size(min = 1, max = 128)String>>undefined();

  public SubscriptionRequest() { 
  }

  public SubscriptionRequest clientName(@javax.annotation.Nonnull String clientName) {
    this.clientName = clientName;
    return this;
  }

  /**
   * User generated identifier, may be VEN identifier provisioned out-of-band.
   * @return clientName
   */
  @javax.annotation.Nonnull
  @NotNull
 @Size(min=1,max=128)
  @JsonProperty(JSON_PROPERTY_CLIENT_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getClientName() {
    return clientName;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientName(@javax.annotation.Nonnull String clientName) {
    this.clientName = clientName;
  }


  public SubscriptionRequest programID(@javax.annotation.Nullable String programID) {
    this.programID = programID;
    return this;
  }

  /**
   * URL safe VTN assigned object ID.
   * @return programID
   */
  @javax.annotation.Nullable
 @Pattern(regexp="^[a-zA-Z0-9_-]*$") @Size(min=1,max=128)
  @JsonProperty(JSON_PROPERTY_PROGRAM_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getProgramID() {
    return programID;
  }


  @JsonProperty(JSON_PROPERTY_PROGRAM_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProgramID(@javax.annotation.Nullable String programID) {
    this.programID = programID;
  }


  public SubscriptionRequest objectOperations(@javax.annotation.Nonnull List<@Valid SubscriptionRequestObjectOperationsInner> objectOperations) {
    this.objectOperations = objectOperations;
    return this;
  }

  public SubscriptionRequest addObjectOperationsItem(SubscriptionRequestObjectOperationsInner objectOperationsItem) {
    if (this.objectOperations == null) {
      this.objectOperations = new ArrayList<>();
    }
    this.objectOperations.add(objectOperationsItem);
    return this;
  }

  /**
   * list of objects and operations to subscribe to.
   * @return objectOperations
   */
  @javax.annotation.Nonnull
  @NotNull
  @Valid

  @JsonProperty(JSON_PROPERTY_OBJECT_OPERATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<@Valid SubscriptionRequestObjectOperationsInner> getObjectOperations() {
    return objectOperations;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT_OPERATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObjectOperations(@javax.annotation.Nonnull List<@Valid SubscriptionRequestObjectOperationsInner> objectOperations) {
    this.objectOperations = objectOperations;
  }


  public SubscriptionRequest targets(@javax.annotation.Nullable List<@Size(min = 1, max = 128)String> targets) {
    this.targets = JsonNullable.<List<@Size(min = 1, max = 128)String>>of(targets);
    return this;
  }

  public SubscriptionRequest addTargetsItem(String targetsItem) {
    if (this.targets == null || !this.targets.isPresent()) {
      this.targets = JsonNullable.<List<@Size(min = 1, max = 128)String>>of(new ArrayList<>());
    }
    try {
      this.targets.get().add(targetsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * A list of target objects. Used by server to filter notifications.
   * @return targets
   */
  @javax.annotation.Nullable

  @JsonIgnore
  public List<@Size(min = 1, max = 128)String> getTargets() {
        return targets.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TARGETS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<@Size(min = 1, max = 128)String>> getTargets_JsonNullable() {
    return targets;
  }
  
  @JsonProperty(JSON_PROPERTY_TARGETS)
  public void setTargets_JsonNullable(JsonNullable<List<@Size(min = 1, max = 128)String>> targets) {
    this.targets = targets;
  }

  public void setTargets(@javax.annotation.Nullable List<@Size(min = 1, max = 128)String> targets) {
    this.targets = JsonNullable.<List<@Size(min = 1, max = 128)String>>of(targets);
  }


  /**
   * Return true if this subscriptionRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionRequest subscriptionRequest = (SubscriptionRequest) o;
    return Objects.equals(this.clientName, subscriptionRequest.clientName) &&
        Objects.equals(this.programID, subscriptionRequest.programID) &&
        Objects.equals(this.objectOperations, subscriptionRequest.objectOperations) &&
        equalsNullable(this.targets, subscriptionRequest.targets);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientName, programID, objectOperations, hashCodeNullable(targets));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionRequest {\n");
    sb.append("    clientName: ").append(toIndentedString(clientName)).append("\n");
    sb.append("    programID: ").append(toIndentedString(programID)).append("\n");
    sb.append("    objectOperations: ").append(toIndentedString(objectOperations)).append("\n");
    sb.append("    targets: ").append(toIndentedString(targets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `clientName` to the URL query string
    if (getClientName() != null) {
      joiner.add(String.format("%sclientName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getClientName()))));
    }

    // add `programID` to the URL query string
    if (getProgramID() != null) {
      joiner.add(String.format("%sprogramID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProgramID()))));
    }

    // add `objectOperations` to the URL query string
    if (getObjectOperations() != null) {
      for (int i = 0; i < getObjectOperations().size(); i++) {
        if (getObjectOperations().get(i) != null) {
          joiner.add(getObjectOperations().get(i).toUrlQueryString(String.format("%sobjectOperations%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `targets` to the URL query string
    if (getTargets() != null) {
      for (int i = 0; i < getTargets().size(); i++) {
        joiner.add(String.format("%stargets%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getTargets().get(i)))));
      }
    }

    return joiner.toString();
  }

    public static class Builder {

    private SubscriptionRequest instance;

    public Builder() {
      this(new SubscriptionRequest());
    }

    protected Builder(SubscriptionRequest instance) {
      this.instance = instance;
    }

    public SubscriptionRequest.Builder clientName(String clientName) {
      this.instance.clientName = clientName;
      return this;
    }
    public SubscriptionRequest.Builder programID(String programID) {
      this.instance.programID = programID;
      return this;
    }
    public SubscriptionRequest.Builder objectOperations(List<SubscriptionRequestObjectOperationsInner> objectOperations) {
      this.instance.objectOperations = objectOperations;
      return this;
    }
    public SubscriptionRequest.Builder targets(List<String> targets) {
      this.instance.targets = JsonNullable.<List<String>>of(targets);
      return this;
    }
    public SubscriptionRequest.Builder targets(JsonNullable<List<String>> targets) {
      this.instance.targets = targets;
      return this;
    }


    /**
    * returns a built SubscriptionRequest instance.
    *
    * The builder is not reusable.
    */
    public SubscriptionRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static SubscriptionRequest.Builder builder() {
    return new SubscriptionRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public SubscriptionRequest.Builder toBuilder() {
    return new SubscriptionRequest.Builder()
      .clientName(getClientName())
      .programID(getProgramID())
      .objectOperations(getObjectOperations())
      .targets(getTargets());
  }

}

