/*
 * OpenADR 3 API
 * The OpenADR 3 API supports energy retailer to energy customer Demand Response programs. See OpenADR 3 User Guide and Definitions for detailed descriptions of usage. The API includes the following capabilities and operations:  __Manage programs:__  * Create/Update/Delete a program * Search programs  __Manage events:__  * Create/Update/Delete an event * Search events  __Manage reports:__  * Create/Update/Delete a report * Search reports  __Manage subscriptions:__  * Create/Update/Delete subscriptions to programs, events, and reports * Search subscriptions * Subscriptions allows clients to register a callback URL (webhook) to be notified   on the change of state of a resource  __Manage vens:__  * Create/Update/Delete vens and ven resources * Search ven and ven resources  __List notifiers:__  * List all notification protocols, and for each notifier, usage details  __List MQTT notifier object topic names:__  * List all MQTT broker topic names for an object and the operations upon the object  __Manage tokens:__  * Obtain an access token * This endpoint is provided as a convenience and may be neglected in a commercial implementation 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@openadr.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.clean_energy_tools.openadr_3_types.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.clean_energy_tools.openadr_3_types.model.ValuesMap;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;


import io.github.clean_energy_tools.openadr_3_types.client.ApiClient;
/**
 * Business Logic provided representation of ven resource. 
 */
@JsonPropertyOrder({
  VenResourceRequest.JSON_PROPERTY_OBJECT_TYPE,
  VenResourceRequest.JSON_PROPERTY_RESOURCE_NAME,
  VenResourceRequest.JSON_PROPERTY_VEN_I_D,
  VenResourceRequest.JSON_PROPERTY_ATTRIBUTES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-09-23T09:35:23.176897405+03:00[Europe/Bucharest]", comments = "Generator version: 7.14.0")
public class VenResourceRequest {
  /**
   * Used as discriminator.
   */
  public enum ObjectTypeEnum {
    VEN_RESOURCE_REQUEST(String.valueOf("VEN_RESOURCE_REQUEST"));

    private String value;

    ObjectTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ObjectTypeEnum fromValue(String value) {
      for (ObjectTypeEnum b : ObjectTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OBJECT_TYPE = "objectType";
  @javax.annotation.Nonnull
  private ObjectTypeEnum objectType;

  public static final String JSON_PROPERTY_RESOURCE_NAME = "resourceName";
  @javax.annotation.Nonnull
  private String resourceName;

  public static final String JSON_PROPERTY_VEN_I_D = "venID";
  @javax.annotation.Nonnull
  private String venID;

  public static final String JSON_PROPERTY_ATTRIBUTES = "attributes";
  private JsonNullable<List<@Valid ValuesMap>> attributes = JsonNullable.<List<@Valid ValuesMap>>undefined();

  public VenResourceRequest() { 
  }

  public VenResourceRequest objectType(@javax.annotation.Nonnull ObjectTypeEnum objectType) {
    this.objectType = objectType;
    return this;
  }

  /**
   * Used as discriminator.
   * @return objectType
   */
  @javax.annotation.Nonnull
  @NotNull

  @JsonProperty(JSON_PROPERTY_OBJECT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ObjectTypeEnum getObjectType() {
    return objectType;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObjectType(@javax.annotation.Nonnull ObjectTypeEnum objectType) {
    this.objectType = objectType;
  }


  public VenResourceRequest resourceName(@javax.annotation.Nonnull String resourceName) {
    this.resourceName = resourceName;
    return this;
  }

  /**
   * User generated identifier. A value of AGGREGATED_REPORT indicates an aggregation of more that one resource&#39;s data
   * @return resourceName
   */
  @javax.annotation.Nonnull
  @NotNull
 @Size(min=1,max=128)
  @JsonProperty(JSON_PROPERTY_RESOURCE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getResourceName() {
    return resourceName;
  }


  @JsonProperty(JSON_PROPERTY_RESOURCE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResourceName(@javax.annotation.Nonnull String resourceName) {
    this.resourceName = resourceName;
  }


  public VenResourceRequest venID(@javax.annotation.Nonnull String venID) {
    this.venID = venID;
    return this;
  }

  /**
   * URL safe VTN assigned object ID.
   * @return venID
   */
  @javax.annotation.Nonnull
  @NotNull
 @Pattern(regexp="^[a-zA-Z0-9_-]*$") @Size(min=1,max=128)
  @JsonProperty(JSON_PROPERTY_VEN_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getVenID() {
    return venID;
  }


  @JsonProperty(JSON_PROPERTY_VEN_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVenID(@javax.annotation.Nonnull String venID) {
    this.venID = venID;
  }


  public VenResourceRequest attributes(@javax.annotation.Nullable List<@Valid ValuesMap> attributes) {
    this.attributes = JsonNullable.<List<@Valid ValuesMap>>of(attributes);
    return this;
  }

  public VenResourceRequest addAttributesItem(ValuesMap attributesItem) {
    if (this.attributes == null || !this.attributes.isPresent()) {
      this.attributes = JsonNullable.<List<@Valid ValuesMap>>of(new ArrayList<>());
    }
    try {
      this.attributes.get().add(attributesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * A list of valuesMap objects describing attributes.
   * @return attributes
   */
  @javax.annotation.Nullable
  @Valid

  @JsonIgnore
  public List<@Valid ValuesMap> getAttributes() {
        return attributes.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<@Valid ValuesMap>> getAttributes_JsonNullable() {
    return attributes;
  }
  
  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  public void setAttributes_JsonNullable(JsonNullable<List<@Valid ValuesMap>> attributes) {
    this.attributes = attributes;
  }

  public void setAttributes(@javax.annotation.Nullable List<@Valid ValuesMap> attributes) {
    this.attributes = JsonNullable.<List<@Valid ValuesMap>>of(attributes);
  }


  /**
   * Return true if this VenResourceRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VenResourceRequest venResourceRequest = (VenResourceRequest) o;
    return Objects.equals(this.objectType, venResourceRequest.objectType) &&
        Objects.equals(this.resourceName, venResourceRequest.resourceName) &&
        Objects.equals(this.venID, venResourceRequest.venID) &&
        equalsNullable(this.attributes, venResourceRequest.attributes);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(objectType, resourceName, venID, hashCodeNullable(attributes));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VenResourceRequest {\n");
    sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
    sb.append("    resourceName: ").append(toIndentedString(resourceName)).append("\n");
    sb.append("    venID: ").append(toIndentedString(venID)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `objectType` to the URL query string
    if (getObjectType() != null) {
      joiner.add(String.format("%sobjectType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getObjectType()))));
    }

    // add `resourceName` to the URL query string
    if (getResourceName() != null) {
      joiner.add(String.format("%sresourceName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResourceName()))));
    }

    // add `venID` to the URL query string
    if (getVenID() != null) {
      joiner.add(String.format("%svenID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVenID()))));
    }

    // add `attributes` to the URL query string
    if (getAttributes() != null) {
      for (int i = 0; i < getAttributes().size(); i++) {
        if (getAttributes().get(i) != null) {
          joiner.add(getAttributes().get(i).toUrlQueryString(String.format("%sattributes%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

    public static class Builder {

    private VenResourceRequest instance;

    public Builder() {
      this(new VenResourceRequest());
    }

    protected Builder(VenResourceRequest instance) {
      this.instance = instance;
    }

    public VenResourceRequest.Builder objectType(ObjectTypeEnum objectType) {
      this.instance.objectType = objectType;
      return this;
    }
    public VenResourceRequest.Builder resourceName(String resourceName) {
      this.instance.resourceName = resourceName;
      return this;
    }
    public VenResourceRequest.Builder venID(String venID) {
      this.instance.venID = venID;
      return this;
    }
    public VenResourceRequest.Builder attributes(List<ValuesMap> attributes) {
      this.instance.attributes = JsonNullable.<List<ValuesMap>>of(attributes);
      return this;
    }
    public VenResourceRequest.Builder attributes(JsonNullable<List<ValuesMap>> attributes) {
      this.instance.attributes = attributes;
      return this;
    }


    /**
    * returns a built VenResourceRequest instance.
    *
    * The builder is not reusable.
    */
    public VenResourceRequest build() {
      try {
        return this.instance;
      } finally {
        // ensure that this.instance is not reused
        this.instance = null;
      }
    }

    @Override
    public String toString() {
      return getClass() + "=(" + instance + ")";
    }
  }

  /**
  * Create a builder with no initialized field.
  */
  public static VenResourceRequest.Builder builder() {
    return new VenResourceRequest.Builder();
  }

  /**
  * Create a builder with a shallow copy of this instance.
  */
  public VenResourceRequest.Builder toBuilder() {
    return new VenResourceRequest.Builder()
      .objectType(getObjectType())
      .resourceName(getResourceName())
      .venID(getVenID())
      .attributes(getAttributes());
  }

}

